// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/oapi-codegen/runtime"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Valid indicates whether the value is a known member of the GetCrmIntegrations200JSONResponseBodyAnswered enum.
func (e GetCrmIntegrations200JSONResponseBodyAnswered) Valid() bool {
	switch e {
	case GetCrmIntegrations200JSONResponseBodyAnsweredOff:
		return true
	case GetCrmIntegrations200JSONResponseBodyAnsweredOn:
		return true
	default:
		return false
	}
}

// Valid indicates whether the value is a known member of the GetCrmIntegrations200JSONResponseBodyHangup enum.
func (e GetCrmIntegrations200JSONResponseBodyHangup) Valid() bool {
	switch e {
	case GetCrmIntegrations200JSONResponseBodyHangupOff:
		return true
	case GetCrmIntegrations200JSONResponseBodyHangupOn:
		return true
	default:
		return false
	}
}

// Valid indicates whether the value is a known member of the GetCrmIntegrations200JSONResponseBodyRinging enum.
func (e GetCrmIntegrations200JSONResponseBodyRinging) Valid() bool {
	switch e {
	case GetCrmIntegrations200JSONResponseBodyRingingOff:
		return true
	case GetCrmIntegrations200JSONResponseBodyRingingOn:
		return true
	default:
		return false
	}
}

// GetCrmIntegrations CRM Entegrasyon Ayarlarını Getirme
//
// Çağrı olayları (çalma, cevaplanma, kapanma) için mevcut CRM webhook entegrasyon ayarlarını getirir. Bu endpoint ile hangi olaylar için webhook bildirimleri aktif olduğunu ve webhook URL'ini öğrenebilirsiniz.
//
// Corresponds with GET /crm_integrations (the `GetCrmIntegrations` operationId).
func (c *Client) GetCrmIntegrations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCrmIntegrationsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateCrmIntegrations CRM Entegrasyon Ayarlarını Güncelleme
//
// Çağrı olayları için CRM webhook entegrasyon ayarlarını günceller. Çalma, cevaplanma ve kapanma olayları için bildirimleri etkinleştirir veya devre dışı bırakır. Webhook URL'i de güncellenebilir.
//
// Corresponds with POST /crm_integrations (the `UpdateCrmIntegrations` operationId).
func (c *Client) UpdateCrmIntegrations(ctx context.Context, params *UpdateCrmIntegrationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateCrmIntegrationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// WebhookPayloadExamples CRM Webhook Payload Örnekleri
//
// CRM entegrasyonu aktif olduğunda gönderilen webhook payload örnekleri. Bu endpoint gerçek bir API değildir, sadece dokümantasyon amaçlıdır.
//
// Corresponds with GET /webhook-payload-examples (the `WebhookPayloadExamples` operationId).
func (c *Client) WebhookPayloadExamples(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWebhookPayloadExamplesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCrmIntegrationsRequest constructs an http.Request for the GetCrmIntegrations method
func NewGetCrmIntegrationsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/crm_integrations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateCrmIntegrationsRequest constructs an http.Request for the UpdateCrmIntegrations method
func NewUpdateCrmIntegrationsRequest(server string, params *UpdateCrmIntegrationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/crm_integrations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Ringing != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "ringing", *params.Ringing, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Answered != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "answered", *params.Answered, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Hangup != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "hangup", *params.Hangup, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.NotificationUrl != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "notification_url", *params.NotificationUrl, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewWebhookPayloadExamplesRequest constructs an http.Request for the WebhookPayloadExamples method
func NewWebhookPayloadExamplesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/webhook-payload-examples")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCrmIntegrationsResponse) GetJSON200() *struct {
	// Answered Çağrı cevaplanma olayları için webhook bildirimi (on: aktif, off: pasif)
	Answered GetCrmIntegrations200JSONResponseBodyAnswered `json:"answered"`

	// Hangup Çağrı kapanma olayları için webhook bildirimi (on: aktif, off: pasif)
	Hangup GetCrmIntegrations200JSONResponseBodyHangup `json:"hangup"`

	// NotificationUrl CRM bildirimlerinin gönderileceği webhook URL adresi
	NotificationUrl string `json:"notification_url"`

	// Ringing Çağrı çalma olayları için webhook bildirimi (on: aktif, off: pasif)
	Ringing GetCrmIntegrations200JSONResponseBodyRinging `json:"ringing"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetCrmIntegrationsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCrmIntegrationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCrmIntegrationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCrmIntegrationsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBody returns the raw response body bytes
func (r UpdateCrmIntegrationsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdateCrmIntegrationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateCrmIntegrationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateCrmIntegrationsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r WebhookPayloadExamplesResponse) GetJSON200() *struct {
	// AnsweredEvent Çağrı cevaplandığında gönderilen payload
	AnsweredEvent *struct {
		AnswerTime   *string `json:"answer_time,omitempty"`
		CallId       *string `json:"call_id,omitempty"`
		CalledNumber *string `json:"called_number,omitempty"`
		CallerNumber *string `json:"caller_number,omitempty"`
		Event        *string `json:"event,omitempty"`
	} `json:"answered_event,omitempty"`

	// HangupEvent Çağrı sonlandığında gönderilen payload
	HangupEvent *struct {
		CallId       *string `json:"call_id,omitempty"`
		CalledNumber *string `json:"called_number,omitempty"`
		CallerNumber *string `json:"caller_number,omitempty"`
		Duration     *int    `json:"duration,omitempty"`
		Event        *string `json:"event,omitempty"`
		HangupCause  *string `json:"hangup_cause,omitempty"`
	} `json:"hangup_event,omitempty"`

	// RingingEvent Çağrı çalmaya başladığında gönderilen payload
	RingingEvent *struct {
		CallId       *string `json:"call_id,omitempty"`
		CalledNumber *string `json:"called_number,omitempty"`
		CallerNumber *string `json:"caller_number,omitempty"`
		Event        *string `json:"event,omitempty"`
		Timestamp    *string `json:"timestamp,omitempty"`
	} `json:"ringing_event,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r WebhookPayloadExamplesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r WebhookPayloadExamplesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WebhookPayloadExamplesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r WebhookPayloadExamplesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetCrmIntegrationsWithResponse CRM Entegrasyon Ayarlarını Getirme
//
// Çağrı olayları (çalma, cevaplanma, kapanma) için mevcut CRM webhook entegrasyon ayarlarını getirir. Bu endpoint ile hangi olaylar için webhook bildirimleri aktif olduğunu ve webhook URL'ini öğrenebilirsiniz.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /crm_integrations (the `GetCrmIntegrations` operationId).
func (c *ClientWithResponses) GetCrmIntegrationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCrmIntegrationsResponse, error) {
	rsp, err := c.GetCrmIntegrations(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCrmIntegrationsResponse(rsp)
}

// UpdateCrmIntegrationsWithResponse CRM Entegrasyon Ayarlarını Güncelleme
//
// Çağrı olayları için CRM webhook entegrasyon ayarlarını günceller. Çalma, cevaplanma ve kapanma olayları için bildirimleri etkinleştirir veya devre dışı bırakır. Webhook URL'i de güncellenebilir.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /crm_integrations (the `UpdateCrmIntegrations` operationId).
func (c *ClientWithResponses) UpdateCrmIntegrationsWithResponse(ctx context.Context, params *UpdateCrmIntegrationsParams, reqEditors ...RequestEditorFn) (*UpdateCrmIntegrationsResponse, error) {
	rsp, err := c.UpdateCrmIntegrations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateCrmIntegrationsResponse(rsp)
}

// WebhookPayloadExamplesWithResponse CRM Webhook Payload Örnekleri
//
// CRM entegrasyonu aktif olduğunda gönderilen webhook payload örnekleri. Bu endpoint gerçek bir API değildir, sadece dokümantasyon amaçlıdır.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /webhook-payload-examples (the `WebhookPayloadExamples` operationId).
func (c *ClientWithResponses) WebhookPayloadExamplesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*WebhookPayloadExamplesResponse, error) {
	rsp, err := c.WebhookPayloadExamples(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWebhookPayloadExamplesResponse(rsp)
}

// ParseGetCrmIntegrationsResponse parses an HTTP response from a GetCrmIntegrationsWithResponse call
func ParseGetCrmIntegrationsResponse(rsp *http.Response) (*GetCrmIntegrationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCrmIntegrationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Answered Çağrı cevaplanma olayları için webhook bildirimi (on: aktif, off: pasif)
			Answered GetCrmIntegrations200JSONResponseBodyAnswered `json:"answered"`

			// Hangup Çağrı kapanma olayları için webhook bildirimi (on: aktif, off: pasif)
			Hangup GetCrmIntegrations200JSONResponseBodyHangup `json:"hangup"`

			// NotificationUrl CRM bildirimlerinin gönderileceği webhook URL adresi
			NotificationUrl string `json:"notification_url"`

			// Ringing Çağrı çalma olayları için webhook bildirimi (on: aktif, off: pasif)
			Ringing GetCrmIntegrations200JSONResponseBodyRinging `json:"ringing"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdateCrmIntegrationsResponse parses an HTTP response from a UpdateCrmIntegrationsWithResponse call
func ParseUpdateCrmIntegrationsResponse(rsp *http.Response) (*UpdateCrmIntegrationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateCrmIntegrationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseWebhookPayloadExamplesResponse parses an HTTP response from a WebhookPayloadExamplesWithResponse call
func ParseWebhookPayloadExamplesResponse(rsp *http.Response) (*WebhookPayloadExamplesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WebhookPayloadExamplesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// AnsweredEvent Çağrı cevaplandığında gönderilen payload
			AnsweredEvent *struct {
				AnswerTime   *string `json:"answer_time,omitempty"`
				CallId       *string `json:"call_id,omitempty"`
				CalledNumber *string `json:"called_number,omitempty"`
				CallerNumber *string `json:"caller_number,omitempty"`
				Event        *string `json:"event,omitempty"`
			} `json:"answered_event,omitempty"`

			// HangupEvent Çağrı sonlandığında gönderilen payload
			HangupEvent *struct {
				CallId       *string `json:"call_id,omitempty"`
				CalledNumber *string `json:"called_number,omitempty"`
				CallerNumber *string `json:"caller_number,omitempty"`
				Duration     *int    `json:"duration,omitempty"`
				Event        *string `json:"event,omitempty"`
				HangupCause  *string `json:"hangup_cause,omitempty"`
			} `json:"hangup_event,omitempty"`

			// RingingEvent Çağrı çalmaya başladığında gönderilen payload
			RingingEvent *struct {
				CallId       *string `json:"call_id,omitempty"`
				CalledNumber *string `json:"called_number,omitempty"`
				CallerNumber *string `json:"caller_number,omitempty"`
				Event        *string `json:"event,omitempty"`
				Timestamp    *string `json:"timestamp,omitempty"`
			} `json:"ringing_event,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
