// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strings"
)

// DeleteContactWithResponse Kişi Silme
//
// Mevcut bir kişiyi siler. Google Kişiler entegrasyonunun kapalı olması gerekir. DELETE metodu ile api.bulutsantralim.com/contacts/{id} adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /contacts/{id} (the `DeleteContact` operationId).
func (c *ClientWithResponses) DeleteContactWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteContactResponse, error) {
	rsp, err := c.DeleteContact(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteContactResponse(rsp)
}

// UpdateContactWithResponse Kişi Güncelleme
//
// Mevcut bir kişiyi günceller. Google Kişiler entegrasyonunun kapalı olması gerekir. Kişi eklerken kullanabileceğiniz tüm parametreler güncelleme için de geçerlidir. PATCH metodu ile api.bulutsantralim.com/contacts/{id} adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /contacts/{id} (the `UpdateContact` operationId).
func (c *ClientWithResponses) UpdateContactWithResponse(ctx context.Context, id int, params *UpdateContactParams, reqEditors ...RequestEditorFn) (*UpdateContactResponse, error) {
	rsp, err := c.UpdateContact(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateContactResponse(rsp)
}

// ParseListContactGroupsResponse parses an HTTP response from a ListContactGroupsWithResponse call
func ParseListContactGroupsResponse(rsp *http.Response) (*ListContactGroupsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListContactGroupsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct {
			// Id Grubun benzersiz kimlik numarası
			Id int `json:"id"`

			// Name Grup adı
			Name string `json:"name"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateContactGroupResponse parses an HTTP response from a CreateContactGroupWithResponse call
func ParseCreateContactGroupResponse(rsp *http.Response) (*CreateContactGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateContactGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDeleteContactGroupResponse parses an HTTP response from a DeleteContactGroupWithResponse call
func ParseDeleteContactGroupResponse(rsp *http.Response) (*DeleteContactGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteContactGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUpdateContactGroupResponse parses an HTTP response from a UpdateContactGroupWithResponse call
func ParseUpdateContactGroupResponse(rsp *http.Response) (*UpdateContactGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateContactGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListContactsResponse parses an HTTP response from a ListContactsWithResponse call
func ParseListContactsResponse(rsp *http.Response) (*ListContactsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListContactsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Contacts []struct {
				// Birthday Doğum günü
				Birthday *string `json:"birthday,omitempty"`

				// BirthdaySms Doğum gününde otomatik mesaj gönderimi. 'true' veya 'false' döner
				BirthdaySms *bool `json:"birthday_sms,omitempty"`

				// CompanyName Firma adı
				CompanyName *string `json:"company_name,omitempty"`

				// Description Açıklama
				Description *string `json:"description,omitempty"`

				// Email E-posta adresi
				Email string `json:"email"`

				// Fax Fax numarası
				Fax *string `json:"fax,omitempty"`

				// Gender Cinsiyet
				Gender *string `json:"gender,omitempty"`

				// GroupIds Kişinin eklendiği gruplar
				GroupIds *[]int `json:"group_ids,omitempty"`

				// Id ID değeri. Bu değeri kullanarak Kişi silme veya güncelleme işlemlerini gerçekleştirebilirsiniz
				Id int `json:"id"`

				// MonthlySmsDay Kişiye aylık otomatik SMS gönderilecek gün. 0-31 arası rakam veya 'null' döner
				MonthlySmsDay *int `json:"monthly_sms_day,omitempty"`

				// MonthlySmsMessage Aylık SMS mesajı
				MonthlySmsMessage *string `json:"monthly_sms_message,omitempty"`

				// Name Ad
				Name string `json:"name"`

				// Note1 Kişiyle ilgili notlar
				Note1 *string `json:"note1,omitempty"`

				// Note2 Kişiyle ilgili notlar 2
				Note2 *string `json:"note2,omitempty"`

				// Note3 Kişiyle ilgili notlar 3
				Note3 *string `json:"note3,omitempty"`

				// Note4 Kişiyle ilgili notlar 4
				Note4 *string `json:"note4,omitempty"`

				// Phone GSM numarası 1
				Phone string `json:"phone"`

				// Phone1 GSM numarası 2
				Phone1 *string `json:"phone1,omitempty"`

				// Phone2 Ek telefon numarası
				Phone2 *string `json:"phone2,omitempty"`

				// Surname Soyad
				Surname string `json:"surname"`

				// Tckn TC kimlik numarası
				Tckn *string `json:"tckn,omitempty"`

				// Title Unvan
				Title *string `json:"title,omitempty"`

				// Weddingday Evlilik günü
				Weddingday *string `json:"weddingday,omitempty"`

				// WeddingdaySms Evlilik gününde otomatik mesaj gönderimi. 'true' veya 'false' döner
				WeddingdaySms *bool `json:"weddingday_sms,omitempty"`
			} `json:"contacts"`
			Pagination struct {
				// Limit Listeye verilen sınır
				Limit int `json:"limit"`

				// Page Listenin hangi sayfasında olduğunuz
				Page int `json:"page"`

				// TotalCount Listede dönen kişi sayısı
				TotalCount int `json:"total_count"`

				// TotalPages Listenin kaç sayfadan oluştuğu (total_pages=total_count/limit)
				TotalPages int `json:"total_pages"`
			} `json:"pagination"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateContactResponse parses an HTTP response from a CreateContactWithResponse call
func ParseCreateContactResponse(rsp *http.Response) (*CreateContactResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateContactResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDeleteContactResponse parses an HTTP response from a DeleteContactWithResponse call
func ParseDeleteContactResponse(rsp *http.Response) (*DeleteContactResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteContactResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUpdateContactResponse parses an HTTP response from a UpdateContactWithResponse call
func ParseUpdateContactResponse(rsp *http.Response) (*UpdateContactResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateContactResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
