// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/oapi-codegen/runtime"
	"io"
	"net/http"
	"net/url"
	"strings"
)

func (c *Client) ManageQueueUsers(ctx context.Context, params *ManageQueueUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewManageQueueUsersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetQueueUserList(ctx context.Context, params *GetQueueUserListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQueueUserListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetQueues(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQueuesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetQueuesPending(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQueuesPendingRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func NewManageQueueUsersRequest(server string, params *ManageQueueUsersParams) (*http.Request, error) {
	var err error
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/queue/manage_users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	if params != nil {
		queryValues := queryURL.Query()
		var rawQueryFragments []string// ManageQueueUsers Kuyruğa Dahili Ekleme, Çıkarma veya Yer Değiştirme
		//
		// Santralinizdeki kuyruklara dahili ekleme, çıkarma veya yer değiştirme için kullanılır. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
		//
		// Corresponds with GET /queue/manage_users (the `ManageQueueUsers` operationId).
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "queue_number", params.QueueNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "user_list", params.UserList, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}
	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func NewGetQueueUserListRequest(server string, params *GetQueueUserListParams) (*http.Request, error) {
	var err error
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/queue/user_list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	if params != nil {
		queryValues := queryURL.Query()
		var rawQueryFragments []string// NewGetQueueUserListRequest constructs an http.Request for the GetQueueUserList method
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "queue_number", params.QueueNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}
	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func NewGetQueuesRequest(server string) (*http.Request, error) {
	var err error
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/queues")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func NewGetQueuesPendingRequest(server string) (*http.Request, error) {
	var err error
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/queues/pending")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func (r ManageQueueUsersResponse) GetBody() []byte {// NewGetQueuesRequest constructs an http.Request for the GetQueues method
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r ManageQueueUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r ManageQueueUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r ManageQueueUsersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r GetQueueUserListResponse) GetJSON200() *[]struct// Status returns HTTPResponse.Status
// GetJSON200 returns the response for an HTTP 200 `application/json` response
{
	Name *string `json:"name,omitempty"`
	User *int    `json:"user,omitempty"`
} {
	return r.JSON200
}

func (r GetQueueUserListResponse) GetBody() []byte {// Name Dahili adı
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r GetQueueUserListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r GetQueueUserListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r GetQueueUserListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r GetQueuesResponse) GetJSON200() *[]struct// Status returns HTTPResponse.Status
// GetJSON200 returns the response for an HTTP 200 `application/json` response
{
	Name   *string `json:"name,omitempty"`
	Number *int    `json:"number,omitempty"`
} {
	return r.JSON200
}

func (r GetQueuesResponse) GetBody() []byte {// Name Kuyruk adı
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r GetQueuesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r GetQueuesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r GetQueuesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r GetQueuesPendingResponse) GetJSON200() *[]struct// Status returns HTTPResponse.Status
// GetJSON200 returns the response for an HTTP 200 `application/json` response
{
	CallUuid    *string `json:"call_uuid,omitempty"`
	CallerId    *string `json:"caller_id,omitempty"`
	JoinedAt    *string `json:"joined_at,omitempty"`
	QueueNumber *string `json:"queue_number,omitempty"`
	Uuid        *string `json:"uuid,omitempty"`
	WaitTime    *int    `json:"wait_time,omitempty"`
} {
	return r.JSON200
}

func (r GetQueuesPendingResponse) GetBody() []byte {// CallUuid Çağrı UUID'si
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r GetQueuesPendingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r GetQueuesPendingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r GetQueuesPendingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (c *ClientWithResponses) ManageQueueUsersWithResponse(ctx context.Context, params *ManageQueueUsersParams, reqEditors ...RequestEditorFn) (*ManageQueueUsersResponse, error) {
	rsp, err := c.ManageQueueUsers(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseManageQueueUsersResponse(rsp)
}

func (c *ClientWithResponses) GetQueueUserListWithResponse(ctx context.Context, params *GetQueueUserListParams, reqEditors ...RequestEditorFn) (*GetQueueUserListResponse, error) {
	rsp, err := c.GetQueueUserList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetQueueUserListResponse(rsp)
}

func (c *ClientWithResponses) GetQueuesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetQueuesResponse, error) {
	rsp, err := c.GetQueues(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetQueuesResponse(rsp)
}

func (c *ClientWithResponses) GetQueuesPendingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetQueuesPendingResponse, error) {
	rsp, err := c.GetQueuesPending(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetQueuesPendingResponse(rsp)
}

func ParseManageQueueUsersResponse(rsp *http.Response) (*ManageQueueUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &ManageQueueUsersResponse{Body: bodyBytes, HTTPResponse: rsp}
	return response, nil
}

func ParseGetQueueUserListResponse(rsp *http.Response) (*GetQueueUserListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &GetQueueUserListResponse{Body: bodyBytes, HTTPResponse: rsp}
	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct// Status returns HTTPResponse.Status
		// ParseGetQueueUserListResponse parses an HTTP response from a GetQueueUserListWithResponse call
		{
			Name *string `json:"name,omitempty"`
			User *int    `json:"user,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}
	return response, nil
}

func ParseGetQueuesResponse(rsp *http.Response) (*GetQueuesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &GetQueuesResponse{Body: bodyBytes, HTTPResponse: rsp}
	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct// Name Dahili adı
		// ParseGetQueuesResponse parses an HTTP response from a GetQueuesWithResponse call
		{
			Name   *string `json:"name,omitempty"`
			Number *int    `json:"number,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}
	return response, nil
}

func ParseGetQueuesPendingResponse(rsp *http.Response) (*GetQueuesPendingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &GetQueuesPendingResponse{Body: bodyBytes, HTTPResponse: rsp}
	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct// Name Kuyruk adı
		// ParseGetQueuesPendingResponse parses an HTTP response from a GetQueuesPendingWithResponse call
		{
			CallUuid    *string `json:"call_uuid,omitempty"`
			CallerId    *string `json:"caller_id,omitempty"`
			JoinedAt    *string `json:"joined_at,omitempty"`
			QueueNumber *string `json:"queue_number,omitempty"`
			Uuid        *string `json:"uuid,omitempty"`
			WaitTime    *int    `json:"wait_time,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}
	return response, nil
}

// CallUuid Çağrı UUID'si
// WaitTime Bekleme süresi (saniye)
