// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/oapi-codegen/runtime"
	"io"
	"net/http"
	"net/url"
	"strings"
)

func NewUpdateContactRequest(server string, id int, params *UpdateContactParams) (*http.Request, error) {
	var err error
	var pathParam0 string
	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/contacts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	if params != nil {
		queryValues := queryURL.Query()
		var rawQueryFragments []string// NewUpdateContactRequest constructs an http.Request for the UpdateContact method
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").

		if params.Salutation != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "salutation", *params.Salutation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Name != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "name", *params.Name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Surname != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "surname", *params.Surname, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Tckn != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tckn", *params.Tckn, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Description != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "description", *params.Description, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Phone != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "phone", *params.Phone, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Phone1 != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "phone1", *params.Phone1, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Email != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "email", *params.Email, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Title != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "title", *params.Title, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Phone2 != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "phone2", *params.Phone2, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Fax != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "fax", *params.Fax, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Gender != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "gender", *params.Gender, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Birthday != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "birthday", *params.Birthday, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.BirthdaySms != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "birthday_sms", *params.BirthdaySms, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Weddingday != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "weddingday", *params.Weddingday, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.WeddingdaySms != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "weddingday_sms", *params.WeddingdaySms, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Address != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "address", *params.Address, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Note1 != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "note1", *params.Note1, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Note2 != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "note2", *params.Note2, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Note3 != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "note3", *params.Note3, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Note4 != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "note4", *params.Note4, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.CompanyName != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "company_name", *params.CompanyName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.MonthlySmsDay != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "monthly_sms_day", *params.MonthlySmsDay, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.MonthlySmsMessage != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "monthly_sms_message", *params.MonthlySmsMessage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.GroupIds != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "group_ids", *params.GroupIds, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}
	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func (r ListContactGroupsResponse) GetJSON200() *[]struct// GetJSON200 returns the response for an HTTP 200 `application/json` response
{
	Id   int    `json:"id"`
	Name string `json:"name"`
} {
	return r.JSON200
}

func (r ListContactGroupsResponse) GetBody() []byte {// Id Grubun benzersiz kimlik numarası
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r ListContactGroupsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r ListContactGroupsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r ListContactGroupsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r CreateContactGroupResponse) GetBody() []byte {// Status returns HTTPResponse.Status
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r CreateContactGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r CreateContactGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r CreateContactGroupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r DeleteContactGroupResponse) GetBody() []byte {// Status returns HTTPResponse.Status
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r DeleteContactGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r DeleteContactGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r DeleteContactGroupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r UpdateContactGroupResponse) GetBody() []byte {// Status returns HTTPResponse.Status
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r UpdateContactGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r UpdateContactGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r UpdateContactGroupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r ListContactsResponse) GetJSON200() *struct {
	Contacts []struct// Status returns HTTPResponse.Status
	// GetJSON200 returns the response for an HTTP 200 `application/json` response
	{
		Birthday    *string `json:"birthday,omitempty"`
		BirthdaySms *bool   `json:"birthday_sms,omitempty"`
		CompanyName *string `json:"company_name,omitempty"`
		Description *string `json:"description,omitempty"`
		Email       string  `json:"email"`
		Fax         *string `json:"fax,omitempty"`
		Gender      *string `json:"gender,omitempty"`
		GroupIds    *[]int  `json:"group_ids,omitempty"`// Birthday Doğum günü
		// GroupIds Kişinin eklendiği gruplar

		Id                int     `json:"id"`
		MonthlySmsDay     *int    `json:"monthly_sms_day,omitempty"`
		MonthlySmsMessage *string `json:"monthly_sms_message,omitempty"`
		Name              string  `json:"name"`
		Note1             *string `json:"note1,omitempty"`
		Note2             *string `json:"note2,omitempty"`
		Note3             *string `json:"note3,omitempty"`
		Note4             *string `json:"note4,omitempty"`
		Phone             string  `json:"phone"`
		Phone1            *string `json:"phone1,omitempty"`
		Phone2            *string `json:"phone2,omitempty"`
		Surname           string  `json:"surname"`
		Tckn              *string `json:"tckn,omitempty"`
		Title             *string `json:"title,omitempty"`
		Weddingday        *string `json:"weddingday,omitempty"`
		WeddingdaySms     *bool   `json:"weddingday_sms,omitempty"`
	} `json:"contacts"`
	Pagination struct {
		Limit      int `json:"limit"`
		Page       int `json:"page"`
		TotalCount int `json:"total_count"`
		TotalPages int `json:"total_pages"`
	} `json:"pagination"`
} {
	return r.JSON200
}

func (r ListContactsResponse) GetBody() []byte {// Id ID değeri. Bu değeri kullanarak Kişi silme veya güncelleme işlemlerini gerçekleştirebilirsiniz
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r ListContactsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r ListContactsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r ListContactsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r CreateContactResponse) GetBody() []byte {// Status returns HTTPResponse.Status
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r CreateContactResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r CreateContactResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r CreateContactResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r DeleteContactResponse) GetBody() []byte {// Status returns HTTPResponse.Status
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r DeleteContactResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r DeleteContactResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r DeleteContactResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r UpdateContactResponse) GetBody() []byte {// Status returns HTTPResponse.Status
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r UpdateContactResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r UpdateContactResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r UpdateContactResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (c *ClientWithResponses) ListContactGroupsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListContactGroupsResponse, error) {
	rsp, err := c.ListContactGroups(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListContactGroupsResponse(rsp)
}

func (c *ClientWithResponses) CreateContactGroupWithResponse(ctx context.Context, params *CreateContactGroupParams, reqEditors ...RequestEditorFn) (*CreateContactGroupResponse, error) {
	rsp, err := c.CreateContactGroup(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateContactGroupResponse(rsp)
}

func (c *ClientWithResponses) DeleteContactGroupWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteContactGroupResponse, error) {
	rsp, err := c.DeleteContactGroup(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteContactGroupResponse(rsp)
}

func (c *ClientWithResponses) UpdateContactGroupWithResponse(ctx context.Context, id int, params *UpdateContactGroupParams, reqEditors ...RequestEditorFn) (*UpdateContactGroupResponse, error) {
	rsp, err := c.UpdateContactGroup(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateContactGroupResponse(rsp)
}

func (c *ClientWithResponses) ListContactsWithResponse(ctx context.Context, params *ListContactsParams, reqEditors ...RequestEditorFn) (*ListContactsResponse, error) {
	rsp, err := c.ListContacts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListContactsResponse(rsp)
}

func (c *ClientWithResponses) CreateContactWithResponse(ctx context.Context, params *CreateContactParams, reqEditors ...RequestEditorFn) (*CreateContactResponse, error) {
	rsp, err := c.CreateContact(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateContactResponse(rsp)
}

func (c *ClientWithResponses) DeleteContactWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteContactResponse, error) {
	rsp, err := c.DeleteContact(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteContactResponse(rsp)
}

func (c *ClientWithResponses) UpdateContactWithResponse(ctx context.Context, id int, params *UpdateContactParams, reqEditors ...RequestEditorFn) (*UpdateContactResponse, error) {
	rsp, err := c.UpdateContact(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateContactResponse(rsp)
}

func ParseListContactGroupsResponse(rsp *http.Response) (*ListContactGroupsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &ListContactGroupsResponse{Body: bodyBytes, HTTPResponse: rsp}
	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct// Status returns HTTPResponse.Status
		// ParseListContactGroupsResponse parses an HTTP response from a ListContactGroupsWithResponse call
		{
			Id   int    `json:"id"`
			Name string `json:"name"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}
	return response, nil
}

func ParseCreateContactGroupResponse(rsp *http.Response) (*CreateContactGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &CreateContactGroupResponse{Body: bodyBytes, HTTPResponse: rsp}
	return response, nil
}

func ParseDeleteContactGroupResponse(rsp *http.Response) (*DeleteContactGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &DeleteContactGroupResponse{Body: bodyBytes, HTTPResponse: rsp}
	return response, nil
}

func ParseUpdateContactGroupResponse(rsp *http.Response) (*UpdateContactGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &UpdateContactGroupResponse{Body: bodyBytes, HTTPResponse: rsp}
	return response, nil
}

func ParseListContactsResponse(rsp *http.Response) (*ListContactsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &ListContactsResponse{Body: bodyBytes, HTTPResponse: rsp}
	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Contacts []struct// Id Grubun benzersiz kimlik numarası
			// ParseListContactsResponse parses an HTTP response from a ListContactsWithResponse call
			{
				Birthday    *string `json:"birthday,omitempty"`
				BirthdaySms *bool   `json:"birthday_sms,omitempty"`
				CompanyName *string `json:"company_name,omitempty"`
				Description *string `json:"description,omitempty"`
				Email       string  `json:"email"`
				Fax         *string `json:"fax,omitempty"`
				Gender      *string `json:"gender,omitempty"`
				GroupIds    *[]int  `json:"group_ids,omitempty"`// Birthday Doğum günü
				// GroupIds Kişinin eklendiği gruplar

				Id                int     `json:"id"`
				MonthlySmsDay     *int    `json:"monthly_sms_day,omitempty"`
				MonthlySmsMessage *string `json:"monthly_sms_message,omitempty"`
				Name              string  `json:"name"`
				Note1             *string `json:"note1,omitempty"`
				Note2             *string `json:"note2,omitempty"`
				Note3             *string `json:"note3,omitempty"`
				Note4             *string `json:"note4,omitempty"`
				Phone             string  `json:"phone"`
				Phone1            *string `json:"phone1,omitempty"`
				Phone2            *string `json:"phone2,omitempty"`
				Surname           string  `json:"surname"`
				Tckn              *string `json:"tckn,omitempty"`
				Title             *string `json:"title,omitempty"`
				Weddingday        *string `json:"weddingday,omitempty"`
				WeddingdaySms     *bool   `json:"weddingday_sms,omitempty"`
			} `json:"contacts"`
			Pagination struct {
				Limit      int `json:"limit"`
				Page       int `json:"page"`
				TotalCount int `json:"total_count"`
				TotalPages int `json:"total_pages"`
			} `json:"pagination"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}
	return response, nil
}

func ParseCreateContactResponse(rsp *http.Response) (*CreateContactResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &CreateContactResponse{Body: bodyBytes, HTTPResponse: rsp}
	return response, nil
}

func ParseDeleteContactResponse(rsp *http.Response) (*DeleteContactResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &DeleteContactResponse{Body: bodyBytes, HTTPResponse: rsp}
	return response, nil
}

func ParseUpdateContactResponse(rsp *http.Response) (*UpdateContactResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &UpdateContactResponse{Body: bodyBytes, HTTPResponse: rsp}
	return response, nil
}

// Id ID değeri. Bu değeri kullanarak Kişi silme veya güncelleme işlemlerini gerçekleştirebilirsiniz
// ParseUpdateContactResponse parses an HTTP response from a UpdateContactWithResponse call
