// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import (
	"context"
	"fmt"
	"github.com/oapi-codegen/runtime"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// NewTransferCallRequest constructs an http.Request for the TransferCall method
func NewTransferCallRequest(server string, id string, params *TransferCallParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/transfer/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "user_number", params.UserNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// GetBody returns the raw response body bytes
func (r AnswerCallPostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AnswerCallPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AnswerCallPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AnswerCallPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBody returns the raw response body bytes
func (r AnswerCallResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AnswerCallResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AnswerCallResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AnswerCallResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBody returns the raw response body bytes
func (r CreateBridgeResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateBridgeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateBridgeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateBridgeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBody returns the raw response body bytes
func (r HangupCallResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r HangupCallResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HangupCallResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HangupCallResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBody returns the raw response body bytes
func (r MuteCallResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r MuteCallResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MuteCallResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MuteCallResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBody returns the raw response body bytes
func (r OriginateCallResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r OriginateCallResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OriginateCallResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r OriginateCallResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBody returns the raw response body bytes
func (r OriginateCallPostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r OriginateCallPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OriginateCallPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r OriginateCallPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBody returns the raw response body bytes
func (r TransferCallPostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TransferCallPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TransferCallPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TransferCallPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBody returns the raw response body bytes
func (r TransferCallResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TransferCallResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TransferCallResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TransferCallResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// AnswerCallPostWithBodyWithResponse Çağrıyı Cevaplama (POST)
//
// manual_answer=true parametresi ile başlatılmış bir çağrıyı cevaplamak için HTTP POST metodu ile /answer endpoint'i id parametresi ile çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 döner.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /answer (the `AnswerCallPost` operationId).
func (c *ClientWithResponses) AnswerCallPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AnswerCallPostResponse, error) {
	rsp, err := c.AnswerCallPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAnswerCallPostResponse(rsp)
}

// AnswerCallPostWithResponse Çağrıyı Cevaplama (POST)
//
// manual_answer=true parametresi ile başlatılmış bir çağrıyı cevaplamak için HTTP POST metodu ile /answer endpoint'i id parametresi ile çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 döner.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /answer (the `AnswerCallPost` operationId).
func (c *ClientWithResponses) AnswerCallPostWithResponse(ctx context.Context, body AnswerCallPostJSONRequestBody, reqEditors ...RequestEditorFn) (*AnswerCallPostResponse, error) {
	rsp, err := c.AnswerCallPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAnswerCallPostResponse(rsp)
}

// AnswerCallPostWithFormdataBodyWithResponse Çağrıyı Cevaplama (POST)
//
// manual_answer=true parametresi ile başlatılmış bir çağrıyı cevaplamak için HTTP POST metodu ile /answer endpoint'i id parametresi ile çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 döner.
//
// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /answer (the `AnswerCallPost` operationId).
func (c *ClientWithResponses) AnswerCallPostWithFormdataBodyWithResponse(ctx context.Context, body AnswerCallPostFormdataRequestBody, reqEditors ...RequestEditorFn) (*AnswerCallPostResponse, error) {
	rsp, err := c.AnswerCallPostWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAnswerCallPostResponse(rsp)
}

// AnswerCallWithResponse Çağrıyı Cevaplama (GET)
//
// manual_answer=true parametresi ile başlatılmış ve dahili telefonda çalmakta olan bir çağrıyı API üzerinden cevaplamak için kullanılır. HTTP GET metodu ile /answer/{id} çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 ile +OK veya çağrıya ilişkin bilgi döner. Başarısız olduğunda ilgili hata mesajı body'de döner.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /answer/{id} (the `AnswerCall` operationId).
func (c *ClientWithResponses) AnswerCallWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*AnswerCallResponse, error) {
	rsp, err := c.AnswerCall(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAnswerCallResponse(rsp)
}

// CreateBridgeWithResponse Çağrı Bağlama
//
// Uygulamalarınız üzerinden iki dış numarayı (örn. cep telefonu) arayıp birbiriyle görüştürmek için kullanılır. Kullanım alanları: Müşteriniz ve saha personelinizi görüştürmek istiyorsunuz fakat bilgi güvenliği (örn. KVKK) nedeniyle cep telefonu numaralarının görünmesini istemiyorsunuz (numara maskeleme/gizleme). Müşteriniz ve saha personelinizin yaptığı görüşmeleri raporlamak ve ses kayıtlarını tutmak istiyorsunuz. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /bridge (the `CreateBridge` operationId).
func (c *ClientWithResponses) CreateBridgeWithResponse(ctx context.Context, params *CreateBridgeParams, reqEditors ...RequestEditorFn) (*CreateBridgeResponse, error) {
	rsp, err := c.CreateBridge(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBridgeResponse(rsp)
}

// HangupCallWithResponse Çağrıyı Sonlandırma
//
// Uygulamalarınız üzerinden santralde devam eden bir çağrıyı sonlandırmak için kullanılır. HTTP GET metodu ile api.bulutsantralim.com adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde +OK döner.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hangup/{id} (the `HangupCall` operationId).
func (c *ClientWithResponses) HangupCallWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*HangupCallResponse, error) {
	rsp, err := c.HangupCall(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHangupCallResponse(rsp)
}

// MuteCallWithResponse Çağrıyı Sessize Alma / Sesli Yapma
//
// Santralde devam eden bir çağrıyı sessize almak veya sesli yapmak için kullanılır. HTTP GET metodu ile çağrı UUID'si ve state parametresi kullanılarak mute işlemi gerçekleştirilir.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /mute/{id} (the `MuteCall` operationId).
func (c *ClientWithResponses) MuteCallWithResponse(ctx context.Context, id string, params *MuteCallParams, reqEditors ...RequestEditorFn) (*MuteCallResponse, error) {
	rsp, err := c.MuteCall(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMuteCallResponse(rsp)
}

// OriginateCallWithResponse Çağrı Başlatma (GET)
//
// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
//
// Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
//
// HAZIRLIK:
// Online İşlem Merkezi => Bulut Santralim => Santral Ayarlarım menüsü altından API Anahtarınızı (key) öğrenmelisiniz.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /originate (the `OriginateCall` operationId).
func (c *ClientWithResponses) OriginateCallWithResponse(ctx context.Context, params *OriginateCallParams, reqEditors ...RequestEditorFn) (*OriginateCallResponse, error) {
	rsp, err := c.OriginateCall(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOriginateCallResponse(rsp)
}

// OriginateCallPostWithBodyWithResponse Çağrı Başlatma (POST)
//
// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP POST metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /originate (the `OriginateCallPost` operationId).
func (c *ClientWithResponses) OriginateCallPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OriginateCallPostResponse, error) {
	rsp, err := c.OriginateCallPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOriginateCallPostResponse(rsp)
}

// OriginateCallPostWithResponse Çağrı Başlatma (POST)
//
// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP POST metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /originate (the `OriginateCallPost` operationId).
func (c *ClientWithResponses) OriginateCallPostWithResponse(ctx context.Context, body OriginateCallPostJSONRequestBody, reqEditors ...RequestEditorFn) (*OriginateCallPostResponse, error) {
	rsp, err := c.OriginateCallPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOriginateCallPostResponse(rsp)
}

// OriginateCallPostWithFormdataBodyWithResponse Çağrı Başlatma (POST)
//
// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP POST metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
//
// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /originate (the `OriginateCallPost` operationId).
func (c *ClientWithResponses) OriginateCallPostWithFormdataBodyWithResponse(ctx context.Context, body OriginateCallPostFormdataRequestBody, reqEditors ...RequestEditorFn) (*OriginateCallPostResponse, error) {
	rsp, err := c.OriginateCallPostWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOriginateCallPostResponse(rsp)
}

// TransferCallPostWithResponse Çağrıyı Aktarma (POST)
//
// Santralde devam eden bir çağrıyı başka bir dahiliye aktarmak için kullanılır. POST metodu ile çağrı UUID'si ve hedef dahili kullanılarak aktarım işlemi gerçekleştirilir.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /transfer (the `TransferCallPost` operationId).
func (c *ClientWithResponses) TransferCallPostWithResponse(ctx context.Context, params *TransferCallPostParams, reqEditors ...RequestEditorFn) (*TransferCallPostResponse, error) {
	rsp, err := c.TransferCallPost(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTransferCallPostResponse(rsp)
}

// TransferCallWithResponse Çağrıyı Aktarma (GET)
//
// Santralde devam eden bir çağrıyı aktarmak için kullanılır. HTTP GET metodu ile çağrı UUID'si ve hedef dahili kullanılarak aktarım işlemi gerçekleştirilir. Yeni çağrı başlattığınızda API'den dönen UUID'yi kullanabilirsiniz veya Olay Bildirme ile gelen UUID'leri kullanabilirsiniz.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /transfer/{id} (the `TransferCall` operationId).
func (c *ClientWithResponses) TransferCallWithResponse(ctx context.Context, id string, params *TransferCallParams, reqEditors ...RequestEditorFn) (*TransferCallResponse, error) {
	rsp, err := c.TransferCall(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTransferCallResponse(rsp)
}

// ParseAnswerCallPostResponse parses an HTTP response from a AnswerCallPostWithResponse call
func ParseAnswerCallPostResponse(rsp *http.Response) (*AnswerCallPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AnswerCallPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseAnswerCallResponse parses an HTTP response from a AnswerCallWithResponse call
func ParseAnswerCallResponse(rsp *http.Response) (*AnswerCallResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AnswerCallResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCreateBridgeResponse parses an HTTP response from a CreateBridgeWithResponse call
func ParseCreateBridgeResponse(rsp *http.Response) (*CreateBridgeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateBridgeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHangupCallResponse parses an HTTP response from a HangupCallWithResponse call
func ParseHangupCallResponse(rsp *http.Response) (*HangupCallResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HangupCallResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseMuteCallResponse parses an HTTP response from a MuteCallWithResponse call
func ParseMuteCallResponse(rsp *http.Response) (*MuteCallResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MuteCallResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseOriginateCallResponse parses an HTTP response from a OriginateCallWithResponse call
func ParseOriginateCallResponse(rsp *http.Response) (*OriginateCallResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OriginateCallResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseOriginateCallPostResponse parses an HTTP response from a OriginateCallPostWithResponse call
func ParseOriginateCallPostResponse(rsp *http.Response) (*OriginateCallPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OriginateCallPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTransferCallPostResponse parses an HTTP response from a TransferCallPostWithResponse call
func ParseTransferCallPostResponse(rsp *http.Response) (*TransferCallPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TransferCallPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTransferCallResponse parses an HTTP response from a TransferCallWithResponse call
func ParseTransferCallResponse(rsp *http.Response) (*TransferCallResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TransferCallResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
