// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import (
	"context"
	"io"
	"net/http"
	"time"
)

// Defines values for GetCdrs200JSONResponseBodyCdrsResult.
const (
	AramaIçinSantralUygunDurumdaDeğil GetCdrs200JSONResponseBodyCdrsResult = "Arama için santral uygun durumda değil"
	Cevaplandı                        GetCdrs200JSONResponseBodyCdrsResult = "Cevaplandı"
	Cevapsız                          GetCdrs200JSONResponseBodyCdrsResult = "Cevapsız"
	CihazYönlendirmesi                GetCdrs200JSONResponseBodyCdrsResult = "Cihaz yönlendirmesi"
	CihazlaIletişimSorunu             GetCdrs200JSONResponseBodyCdrsResult = "Cihazla iletişim sorunu"
	DesteklenmeyenKanalTipi           GetCdrs200JSONResponseBodyCdrsResult = "Desteklenmeyen kanal tipi"
	DiğerDahiliCevapladı              GetCdrs200JSONResponseBodyCdrsResult = "Diğer dahili cevapladı"
	GenelHata                         GetCdrs200JSONResponseBodyCdrsResult = "Genel Hata"
	GeçersizJSONKullanımı             GetCdrs200JSONResponseBodyCdrsResult = "Geçersiz JSON kullanımı"
	Hata                              GetCdrs200JSONResponseBodyCdrsResult = "Hata"
	HatalıNumara                      GetCdrs200JSONResponseBodyCdrsResult = "Hatalı Numara"
	KatılımlıAktarım                  GetCdrs200JSONResponseBodyCdrsResult = "Katılımlı aktarım"
	Meşgul                            GetCdrs200JSONResponseBodyCdrsResult = "Meşgul"
	RTPZamanaşımı                     GetCdrs200JSONResponseBodyCdrsResult = "RTP zamanaşımı"
	Reddedildi                        GetCdrs200JSONResponseBodyCdrsResult = "Reddedildi"
	SantralKapatılıyor                GetCdrs200JSONResponseBodyCdrsResult = "Santral kapatılıyor"
	SesKodekleriUyumsuz               GetCdrs200JSONResponseBodyCdrsResult = "Ses kodekleri uyumsuz"
	SesliGörüşmeYapamayanNumara       GetCdrs200JSONResponseBodyCdrsResult = "Sesli görüşme yapamayan numara"
	TanınmayanÇağrıIDNumarası         GetCdrs200JSONResponseBodyCdrsResult = "Tanınmayan Çağrı ID numarası"
	Ulaşılamıyor                      GetCdrs200JSONResponseBodyCdrsResult = "Ulaşılamıyor"
	Vazgeçildi                        GetCdrs200JSONResponseBodyCdrsResult = "Vazgeçildi"
	Zamanaşımı                        GetCdrs200JSONResponseBodyCdrsResult = "Zamanaşımı"
	ÇağrıBağlanamadı                  GetCdrs200JSONResponseBodyCdrsResult = "Çağrı bağlanamadı"
	ÇağrısıÇekildi                    GetCdrs200JSONResponseBodyCdrsResult = "Çağrısı çekildi"
	İYSIzniYok                        GetCdrs200JSONResponseBodyCdrsResult = "İYS izni yok"
	İletişimSorunu                    GetCdrs200JSONResponseBodyCdrsResult = "İletişim sorunu"
)

// IVRKampanyaRaporAlimiFormdataBody defines parameters for IVRKampanyaRaporAlimi.
type IVRKampanyaRaporAlimiFormdataBody struct {
	// CallUuid Tuşlama için yapılan çağrının UUID'si.
	CallUuid *string `form:"call_uuid,omitempty" json:"call_uuid,omitempty"`

	// Digit Aranan kişinin yaptığı tuşlama. Boş string (""): Çağrı başlamadı. 0-9: Geçerli tuşlama. -: timeout. !4: Geçersiz tuşlama.
	Digit *string `form:"digit,omitempty" json:"digit,omitempty"`

	// DomainId Bulutsantral ID'si.
	DomainId *string `form:"domain_id,omitempty" json:"domain_id,omitempty"`

	// IvrCampaignId Otomatik IVR arama kampanyasının ID'si.
	IvrCampaignId *int `form:"ivr_campaign_id,omitempty" json:"ivr_campaign_id,omitempty"`

	// IvrCampaignName Otomatik IVR arama kampanyasının adı.
	IvrCampaignName *string `form:"ivr_campaign_name,omitempty" json:"ivr_campaign_name,omitempty"`

	// IvrLeadId Kampanyadaki numaranın ID'si.
	IvrLeadId *int `form:"ivr_lead_id,omitempty" json:"ivr_lead_id,omitempty"`

	// NotificationDate Bildirimi yapılan olayın gerçekleştiği tarih saat.
	NotificationDate *time.Time `form:"notification_date,omitempty" json:"notification_date,omitempty"`

	// NotificationId Bu bildirime ait unique id.
	NotificationId *int `form:"notification_id,omitempty" json:"notification_id,omitempty"`

	// Phone Aranan telefon numarası.
	Phone *string `form:"phone,omitempty" json:"phone,omitempty"`

	// Status Çağrı durumu. 'Cevaplandı', 'Cevapsız', 'Reddedildi', 'Hata' gibi açıklamaları içerir. 'Cevaplandı' hariç her durum hata olarak yorumlanabilir.
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// OlayBildirmeFormdataBody defines parameters for OlayBildirme.
type OlayBildirmeFormdataBody struct {
	// AnswerStamp Çağrının cevaplandığı zaman.
	AnswerStamp *time.Time `form:"answer_stamp,omitempty" json:"answer_stamp,omitempty"`

	// Answered Kaçan çağrı tespiti için kullanılır. Aranan taraf çağrıyı kabul ettiyse true döner.
	Answered *bool `form:"answered,omitempty" json:"answered,omitempty"`

	// CallUuid Çağrının uuid'si.
	CallUuid *string `form:"call_uuid,omitempty" json:"call_uuid,omitempty"`

	// CallerIdNumber Arayan numara.
	CallerIdNumber *string `form:"caller_id_number,omitempty" json:"caller_id_number,omitempty"`

	// ConnectedUser Bağlanan (telefonu açan) dahili.
	ConnectedUser *string `form:"connected_user,omitempty" json:"connected_user,omitempty"`

	// DestinationNumber Aranan numara.
	DestinationNumber *string `form:"destination_number,omitempty" json:"destination_number,omitempty"`

	// DialedUser Aranan kişinin dahili numarası.
	DialedUser *string `form:"dialed_user,omitempty" json:"dialed_user,omitempty"`

	// Direction Çağrının yönü. internal, inbound yada outbound döner.
	Direction *string `form:"direction,omitempty" json:"direction,omitempty"`

	// DomainId Bulutsantral ID'si.
	DomainId *string `form:"domain_id,omitempty" json:"domain_id,omitempty"`

	// Duration Konuşma süresi.
	Duration *int `form:"duration,omitempty" json:"duration,omitempty"`

	// EndStamp Çağrının sonlandığı zaman.
	EndStamp *time.Time `form:"end_stamp,omitempty" json:"end_stamp,omitempty"`

	// EventType Olay tipi. ringing, answer, hangup veya user_hangup döner.
	EventType *string `form:"event_type,omitempty" json:"event_type,omitempty"`

	// FailurePhrase Çağrı başarısız ise hata mesajı.
	FailurePhrase *string `form:"failure_phrase,omitempty" json:"failure_phrase,omitempty"`

	// FailureStatus Çağrı başarısız ise hata kodu. Bkz. <a href="/developer/errors/cagri-sonuc-kodlari">Çağrı Sonuç Kodları</a>.
	FailureStatus *string `form:"failure_status,omitempty" json:"failure_status,omitempty"`

	// HangupCause Çağrının kapanma sebebi. Alabileceği değerler için <a href="/developer/errors/cagri-sonuc-kodlari">Çağrı Sonuç Kodları</a> sayfasına bakın.
	HangupCause *string `form:"hangup_cause,omitempty" json:"hangup_cause,omitempty"`

	// OutboundCallerIdNumber Arayanın dış numarası.
	OutboundCallerIdNumber *string `form:"outbound_caller_id_number,omitempty" json:"outbound_caller_id_number,omitempty"`

	// Queue Kuyruğun veya Çağrı grubunun numarası.
	Queue *string `form:"queue,omitempty" json:"queue,omitempty"`

	// QueueWaitDuration Kuyrukta bekleme süresi.
	QueueWaitDuration *int `form:"queue_wait_duration,omitempty" json:"queue_wait_duration,omitempty"`

	// RecordingPresent Çağrının ses kaydının olup olmadığı. true yada false döner.
	RecordingPresent *bool `form:"recording_present,omitempty" json:"recording_present,omitempty"`

	// SipHangupDisposition Çağrının kimin tarafından kapatıldığı. caller ya da callee olarak döner.
	SipHangupDisposition *string `form:"sip_hangup_disposition,omitempty" json:"sip_hangup_disposition,omitempty"`

	// StartStamp Çağrının başladığı zaman.
	StartStamp *time.Time `form:"start_stamp,omitempty" json:"start_stamp,omitempty"`
}

// IVRKampanyaRaporAlimiFormdataRequestBody defines body for IVRKampanyaRaporAlimi for application/x-www-form-urlencoded ContentType.
type IVRKampanyaRaporAlimiFormdataRequestBody IVRKampanyaRaporAlimiFormdataBody

// OlayBildirmeFormdataRequestBody defines body for OlayBildirme for application/x-www-form-urlencoded ContentType.
type OlayBildirmeFormdataRequestBody OlayBildirmeFormdataBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// The interface specification for the client above.
type ClientInterface interface {

	// ListAgentStatuses MT Durumlarını ve Üyeliklerini Listeleme
	//
	// Müşteri Temsilcilerinizin durumunu ve hangi kuyruklara üye olduklarını listelemek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/agent_statuses adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde mesajlar döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint, /user_statuses ile aynı hız sınırı havuzunu paylaşır - aynı domain/IP için ikisi birlikte dakikada toplam 2 istek gönderebilirsiniz.
	//
	// Corresponds with GET /agent_statuses (the `ListAgentStatuses` operationId).
	ListAgentStatuses(ctx context.Context, params *ListAgentStatusesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAnnouncements Ses Dosyaları Listesine Erişim
	//
	// Santralinizdeki ses dosyalarının listesine erişmek için kullanılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde ses dosyalarının listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with GET /announcements (the `GetAnnouncements` operationId).
	GetAnnouncements(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAnnouncementWithBody Yeni Ses Dosyası Yükleme
	//
	// Yeni ses dosyası yüklemek için kullanılır. Yeni ses dosyasının ismini ve içeriğinin base64 ile kodlanmış halini POST etmeniz yeterlidir. Başarılı durumda oluşturulan ses dosyasının ID'si döner.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /announcements (the `CreateAnnouncement` operationId).
	CreateAnnouncementWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAnnouncementWithFormdataBody Yeni Ses Dosyası Yükleme
	//
	// Yeni ses dosyası yüklemek için kullanılır. Yeni ses dosyasının ismini ve içeriğinin base64 ile kodlanmış halini POST etmeniz yeterlidir. Başarılı durumda oluşturulan ses dosyasının ID'si döner.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type.
	//
	// Corresponds with POST /announcements (the `CreateAnnouncement` operationId).
	CreateAnnouncementWithFormdataBody(ctx context.Context, body CreateAnnouncementFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAnnouncement Ses Dosyası Silme
	//
	// Ses dosyasını silmek için kullanılır. Ses dosyasının id ile DELETE etmeniz yeterlidir. Başarılı durumda OK döner.
	//
	// Corresponds with DELETE /announcements/{id} (the `DeleteAnnouncement` operationId).
	DeleteAnnouncement(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateAnnouncementWithBody Ses Dosyası Güncelleme
	//
	// Mevcut ses dosyasının adını ve içeriğini güncellemek için kullanılır. Ses dosyasının ismini ve içeriğinin base64 ile kodlanmış halini PATCH etmeniz yeterlidir. Başarılı durumda OK döner.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /announcements/{id} (the `UpdateAnnouncement` operationId).
	UpdateAnnouncementWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateAnnouncementWithFormdataBody Ses Dosyası Güncelleme
	//
	// Mevcut ses dosyasının adını ve içeriğini güncellemek için kullanılır. Ses dosyasının ismini ve içeriğinin base64 ile kodlanmış halini PATCH etmeniz yeterlidir. Başarılı durumda OK döner.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type.
	//
	// Corresponds with PATCH /announcements/{id} (the `UpdateAnnouncement` operationId).
	UpdateAnnouncementWithFormdataBody(ctx context.Context, id string, body UpdateAnnouncementFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AnswerCallPostWithBody Çağrıyı Cevaplama (POST)
	//
	// manual_answer=true parametresi ile başlatılmış bir çağrıyı cevaplamak için HTTP POST metodu ile /answer endpoint'i id parametresi ile çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 döner.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /answer (the `AnswerCallPost` operationId).
	AnswerCallPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AnswerCallPost Çağrıyı Cevaplama (POST)
	//
	// manual_answer=true parametresi ile başlatılmış bir çağrıyı cevaplamak için HTTP POST metodu ile /answer endpoint'i id parametresi ile çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 döner.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /answer (the `AnswerCallPost` operationId).
	AnswerCallPost(ctx context.Context, body AnswerCallPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AnswerCallPostWithFormdataBody Çağrıyı Cevaplama (POST)
	//
	// manual_answer=true parametresi ile başlatılmış bir çağrıyı cevaplamak için HTTP POST metodu ile /answer endpoint'i id parametresi ile çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 döner.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type.
	//
	// Corresponds with POST /answer (the `AnswerCallPost` operationId).
	AnswerCallPostWithFormdataBody(ctx context.Context, body AnswerCallPostFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AnswerCall Çağrıyı Cevaplama (GET)
	//
	// manual_answer=true parametresi ile başlatılmış ve dahili telefonda çalmakta olan bir çağrıyı API üzerinden cevaplamak için kullanılır. HTTP GET metodu ile /answer/{id} çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 ile +OK veya çağrıya ilişkin bilgi döner. Başarısız olduğunda ilgili hata mesajı body'de döner.
	//
	// Corresponds with GET /answer/{id} (the `AnswerCall` operationId).
	AnswerCall(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListBlockedNumbers Kara Listeye Erişim
	//
	// Santralinizdeki kara listedeki numaraların listesine erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/blocked_numbers adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde kara liste döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with GET /blocked_numbers (the `ListBlockedNumbers` operationId).
	ListBlockedNumbers(ctx context.Context, params *ListBlockedNumbersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateBlockedNumber Kara Listeye Ekleme
	//
	// Telefon numarasını kara listeye ekler. Numara kayıt edilmeden önce normalize edilir. POST metodu ile api.bulutsantralim.com/blocked_numbers adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde oluşturulan kaydın ID'si döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with POST /blocked_numbers (the `CreateBlockedNumber` operationId).
	CreateBlockedNumber(ctx context.Context, params *CreateBlockedNumberParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBlockedNumber Kara Listeden Silme
	//
	// Telefon numarasını kara listeden çıkarır. Numara kaldırılmadan önce normalize edilir. DELETE metodu ile api.bulutsantralim.com/blocked_numbers/delete adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde başarı mesajı döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with DELETE /blocked_numbers/delete (the `DeleteBlockedNumber` operationId).
	DeleteBlockedNumber(ctx context.Context, params *DeleteBlockedNumberParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateBridge Çağrı Bağlama
	//
	// Uygulamalarınız üzerinden iki dış numarayı (örn. cep telefonu) arayıp birbiriyle görüştürmek için kullanılır. Kullanım alanları: Müşteriniz ve saha personelinizi görüştürmek istiyorsunuz fakat bilgi güvenliği (örn. KVKK) nedeniyle cep telefonu numaralarının görünmesini istemiyorsunuz (numara maskeleme/gizleme). Müşteriniz ve saha personelinizin yaptığı görüşmeleri raporlamak ve ses kayıtlarını tutmak istiyorsunuz. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
	//
	// Corresponds with GET /bridge (the `CreateBridge` operationId).
	CreateBridge(ctx context.Context, params *CreateBridgeParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCallerIds Dış Numaralar Listesine Erişim
	//
	// Santralinizdeki Arayan Numara olarak kullanabileceğiniz numaraların listesine erişmek için kullanılır.
	//
	// HAZIRLIK:
	// Online İşlem Merkezi => Bulut Santralim => Santral Ayarlarım menüsü altından API Anahtarınızı (key) öğrenmelisiniz.
	//
	// Corresponds with GET /caller_ids (the `GetCallerIds` operationId).
	GetCallerIds(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCdrs Çağrı Detay Kayıtları (CDR) Listesi
	//
	// Farklı filtrelerle ve sayfalama ile çağrı detay kayıtlarını (CDR) listeler. Bu endpoint dakikada en fazla 6 istek ile sınırlıdır.
	//
	// Corresponds with GET /cdrs (the `GetCdrs` operationId).
	GetCdrs(ctx context.Context, params *GetCdrsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCdr Belirli Bir Çağrının Detaylı CDR Kaydı
	//
	// Belirli bir çağrıya ait tüm detayları ve çağrı akışını getirir. Bu endpoint dakikada en fazla 6 istek ile sınırlıdır.
	//
	// Corresponds with GET /cdrs/{id} (the `GetCdr` operationId).
	GetCdr(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListContactGroups Grup Listesine Erişim
	//
	// Santralinizdeki kişi gruplarının listesine erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/contact_groups adresi çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde gruplar listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with GET /contact_groups (the `ListContactGroups` operationId).
	ListContactGroups(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateContactGroup Grup Oluşturma
	//
	// Yeni bir kişi grubu oluşturur. Google Kişiler entegrasyonunun kapalı olması gerekir. POST metodu ile api.bulutsantralim.com/contact_groups adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde oluşturulan grubun ID'si döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with POST /contact_groups (the `CreateContactGroup` operationId).
	CreateContactGroup(ctx context.Context, params *CreateContactGroupParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteContactGroup Grup Silme
	//
	// Mevcut bir kişi grubunu siler. Google Kişiler entegrasyonunun kapalı olması gerekir. DELETE metodu ile api.bulutsantralim.com/contact_groups/{id} adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with DELETE /contact_groups/{id} (the `DeleteContactGroup` operationId).
	DeleteContactGroup(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateContactGroup Grup Güncelleme
	//
	// Mevcut bir kişi grubunu günceller. Google Kişiler entegrasyonunun kapalı olması gerekir. PATCH metodu ile api.bulutsantralim.com/contact_groups/{id} adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with PATCH /contact_groups/{id} (the `UpdateContactGroup` operationId).
	UpdateContactGroup(ctx context.Context, id int, params *UpdateContactGroupParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListContacts Kişiler Listesine Erişim
	//
	// Santralinizdeki kişiler listesine erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/contacts adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde kişiler listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with GET /contacts (the `ListContacts` operationId).
	ListContacts(ctx context.Context, params *ListContactsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateContact Kişi Ekleme
	//
	// Yeni bir kişi oluşturur. Google Kişiler entegrasyonunun kapalı olması gerekir. POST metodu ile api.bulutsantralim.com/contacts adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde oluşturulan kişinin ID'si döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with POST /contacts (the `CreateContact` operationId).
	CreateContact(ctx context.Context, params *CreateContactParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteContact Kişi Silme
	//
	// Mevcut bir kişiyi siler. Google Kişiler entegrasyonunun kapalı olması gerekir. DELETE metodu ile api.bulutsantralim.com/contacts/{id} adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with DELETE /contacts/{id} (the `DeleteContact` operationId).
	DeleteContact(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateContact Kişi Güncelleme
	//
	// Mevcut bir kişiyi günceller. Google Kişiler entegrasyonunun kapalı olması gerekir. Kişi eklerken kullanabileceğiniz tüm parametreler güncelleme için de geçerlidir. PATCH metodu ile api.bulutsantralim.com/contacts/{id} adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with PATCH /contacts/{id} (the `UpdateContact` operationId).
	UpdateContact(ctx context.Context, id int, params *UpdateContactParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCrmIntegrations CRM Entegrasyon Ayarlarını Getirme
	//
	// Çağrı olayları (çalma, cevaplanma, kapanma) için mevcut CRM webhook entegrasyon ayarlarını getirir. Bu endpoint ile hangi olaylar için webhook bildirimleri aktif olduğunu ve webhook URL'ini öğrenebilirsiniz.
	//
	// Corresponds with GET /crm_integrations (the `GetCrmIntegrations` operationId).
	GetCrmIntegrations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateCrmIntegrations CRM Entegrasyon Ayarlarını Güncelleme
	//
	// Çağrı olayları için CRM webhook entegrasyon ayarlarını günceller. Çalma, cevaplanma ve kapanma olayları için bildirimleri etkinleştirir veya devre dışı bırakır. Webhook URL'i de güncellenebilir.
	//
	// Corresponds with POST /crm_integrations (the `UpdateCrmIntegrations` operationId).
	UpdateCrmIntegrations(ctx context.Context, params *UpdateCrmIntegrationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDnd Dahili için Rahatsız Etme (DND) Modunu Ayarlama
	//
	// Kullanıcının dahili numarası için Rahatsız Etme (DND) modunu açar veya kapatır. DND açıkken kullanıcıya gelen çağrılar engellenir.
	//
	// Corresponds with GET /dnd/{id} (the `CreateDnd` operationId).
	CreateDnd(ctx context.Context, id string, params *CreateDndParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListExtensions Dahili Listesi
	//
	// Santralinizdeki tüm dahilileri listelemek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/extensions adresi çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde dahili listesi döner.
	//
	// Corresponds with GET /extensions (the `ListExtensions` operationId).
	ListExtensions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetExtension Dahili Detayı
	//
	// Belirli bir dahilinin detaylarını getirmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/extensions/{id} adresi çağrılır.
	//
	// ÖNEMLİ NOT:
	// Yanıt, dahilinin SIP şifresini (`password`) düz metin olarak içerir. Bu yanıtı güvenli şekilde saklayın ve loglamayın.
	//
	// Corresponds with GET /extensions/{id} (the `GetExtension` operationId).
	GetExtension(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadFaxDocument Faks Belgesi İndirme/Görüntüleme
	//
	// Bu servis, daha önce 'Faks Belgesi URL'si İsteme' ile elde edilen geçici URL üzerinden faks belgesini indirmenizi veya görüntülemenizi sağlar.
	//
	// URL, 1 saat geçerlidir. Herhangi bir kimlik doğrulama gerekmez; güvenlik, URL'nin kendisinde bulunan tek kullanımlık ticket kodu ile sağlanır.
	//
	// Başarılı isteklerde HTTP 200 ile belge dosyası (PDF/TIFF) döner. Hatalı veya süresi dolmuş ticket ile yapılan isteklerde uygun hata mesajı ve HTTP 400 döner.
	//
	// Corresponds with GET /fax_document/{id} (the `DownloadFaxDocument` operationId).
	DownloadFaxDocument(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateFaxDocumentUrl Faks Belgesi URL'si İsteme
	//
	// Başarıyla iletilen faks belgesi için geçici indirme URL'si oluşturur. HTTP POST metodu ile api.bulutsantralim.com/fax_document_url/ adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde belgeye ait URL döner. URL yaşam süresi 1 saattir ve PDF versiyonuna erişim sağlar. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with POST /fax_document_url (the `CreateFaxDocumentUrl` operationId).
	CreateFaxDocumentUrl(ctx context.Context, params *CreateFaxDocumentUrlParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListFaxOrders Tamamlanmamış Faks Gönderimlerinin Listesi
	//
	// Santraldaki tamamlanmamış faks gönderimlerinin listesine erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/fax_orders adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde faks gönderim kayıtları döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with GET /fax_orders (the `ListFaxOrders` operationId).
	ListFaxOrders(ctx context.Context, params *ListFaxOrdersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateFaxOrder Faks Gönderimi
	//
	// Faks göndermek için dosyasının içeriğinin base64 ile kodlanmış halini ve diğer bilgileri POST etmeniz yeterlidir. Uygulamalarınız üzerinden faks göndermek için api.bulutsantralim.com/fax_orders adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 status kodu ile mesajın Body'sinde faks ID döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with POST /fax_orders (the `CreateFaxOrder` operationId).
	CreateFaxOrder(ctx context.Context, params *CreateFaxOrderParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListFdrs Faks Listesine Erişim
	//
	// Santralinizdeki faks detay kayıtlarının listesine erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/fdrs adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde faks kayıtları döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Tarih aralığı 31 günden uzun olamaz.
	//
	// Corresponds with GET /fdrs (the `ListFdrs` operationId).
	ListFdrs(ctx context.Context, params *ListFdrsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HangupCall Çağrıyı Sonlandırma
	//
	// Uygulamalarınız üzerinden santralde devam eden bir çağrıyı sonlandırmak için kullanılır. HTTP GET metodu ile api.bulutsantralim.com adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde +OK döner.
	//
	// Corresponds with GET /hangup/{id} (the `HangupCall` operationId).
	HangupCall(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateIvrCampaignWithBody Otomatik Arama Kampanyası Oluşturma
	//
	// Yeni otomatik arama kampanyası oluşturmak için kullanılır. JSON formatında parametreler ile POST isteği gönderilir. ivr_campaigns endpoint'leri saniyede 2 istek (yaklaşık dakikada 120) limitine tabidir, burst değeri 50'dir.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /ivr_campaigns.json (the `CreateIvrCampaign` operationId).
	CreateIvrCampaignWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateIvrCampaign Otomatik Arama Kampanyası Oluşturma
	//
	// Yeni otomatik arama kampanyası oluşturmak için kullanılır. JSON formatında parametreler ile POST isteği gönderilir. ivr_campaigns endpoint'leri saniyede 2 istek (yaklaşık dakikada 120) limitine tabidir, burst değeri 50'dir.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /ivr_campaigns.json (the `CreateIvrCampaign` operationId).
	CreateIvrCampaign(ctx context.Context, body CreateIvrCampaignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteIvrCampaign Otomatik Arama Kampanyasını Silme
	//
	// Otomatik arama kampanyasını iptal etmek/silmek için kullanılır. Kampanya ID'si ve API anahtarı ile DELETE isteği gönderilir.
	//
	// Corresponds with DELETE /ivr_campaigns/{id}.json (the `DeleteIvrCampaign` operationId).
	DeleteIvrCampaign(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateIvrCampaign Otomatik Arama Kampanyasını Başlatma/Durdurma
	//
	// Otomatik arama kampanyasını durdurmak veya tekrar başlatmak için kullanılır. PATCH ile status=off gönderilirse kampanya durur, status=on gönderilirse tekrar başlar.
	//
	// Corresponds with PATCH /ivr_campaigns/{id}.json (the `UpdateIvrCampaign` operationId).
	UpdateIvrCampaign(ctx context.Context, id string, params *UpdateIvrCampaignParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MuteCall Çağrıyı Sessize Alma / Sesli Yapma
	//
	// Santralde devam eden bir çağrıyı sessize almak veya sesli yapmak için kullanılır. HTTP GET metodu ile çağrı UUID'si ve state parametresi kullanılarak mute işlemi gerçekleştirilir.
	//
	// Corresponds with GET /mute/{id} (the `MuteCall` operationId).
	MuteCall(ctx context.Context, id string, params *MuteCallParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OriginateCall Çağrı Başlatma (GET)
	//
	// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
	//
	// HAZIRLIK:
	// Online İşlem Merkezi => Bulut Santralim => Santral Ayarlarım menüsü altından API Anahtarınızı (key) öğrenmelisiniz.
	//
	// Corresponds with GET /originate (the `OriginateCall` operationId).
	OriginateCall(ctx context.Context, params *OriginateCallParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OriginateCallPostWithBody Çağrı Başlatma (POST)
	//
	// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP POST metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /originate (the `OriginateCallPost` operationId).
	OriginateCallPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OriginateCallPost Çağrı Başlatma (POST)
	//
	// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP POST metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /originate (the `OriginateCallPost` operationId).
	OriginateCallPost(ctx context.Context, body OriginateCallPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OriginateCallPostWithFormdataBody Çağrı Başlatma (POST)
	//
	// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP POST metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type.
	//
	// Corresponds with POST /originate (the `OriginateCallPost` operationId).
	OriginateCallPostWithFormdataBody(ctx context.Context, body OriginateCallPostFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ManageQueueUsers Kuyruğa Dahili Ekleme, Çıkarma veya Yer Değiştirme
	//
	// Santralinizdeki kuyruklara dahili ekleme, çıkarma veya yer değiştirme için kullanılır. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with GET /queue/manage_users (the `ManageQueueUsers` operationId).
	ManageQueueUsers(ctx context.Context, params *ManageQueueUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetQueueUserList Kuyruktaki Dahili Listesine Erişim
	//
	// Santralinizdeki kuyruğun dahili sırasını listeler. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde dahili listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with GET /queue/user_list (the `GetQueueUserList` operationId).
	GetQueueUserList(ctx context.Context, params *GetQueueUserListParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetQueues Kuyruklar Listesine Erişim
	//
	// Santralinizdeki kuyrukların listesine erişmek için kullanılır. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde kuyrukların listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with GET /queues (the `GetQueues` operationId).
	GetQueues(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetQueuesPending Kuyrukta Bekleyenler Listesine Erişim
	//
	// Santralinizdeki kuyrukta bekleyenlerin listesine erişmek için kullanılır. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde kuyrukta bekleyenlerin listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint dakikada en fazla 10 istek ile sınırlıdır.
	//
	// Corresponds with GET /queues/pending (the `GetQueuesPending` operationId).
	GetQueuesPending(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateRecordingUrl Ses Kaydı için Geçici URL Oluşturma
	//
	// Santralinizdeki veya Google Drive'a aktarılmış ses kayıtlarınıza erişmek için geçici bir URL oluşturur. URL 1 saat geçerlidir ve dakikada en fazla 5 istek yapılabilir.
	//
	// Corresponds with POST /recording_url (the `CreateRecordingUrl` operationId).
	CreateRecordingUrl(ctx context.Context, params *CreateRecordingUrlParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TransferCallPost Çağrıyı Aktarma (POST)
	//
	// Santralde devam eden bir çağrıyı başka bir dahiliye aktarmak için kullanılır. POST metodu ile çağrı UUID'si ve hedef dahili kullanılarak aktarım işlemi gerçekleştirilir.
	//
	// Corresponds with POST /transfer (the `TransferCallPost` operationId).
	TransferCallPost(ctx context.Context, params *TransferCallPostParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TransferCall Çağrıyı Aktarma (GET)
	//
	// Santralde devam eden bir çağrıyı aktarmak için kullanılır. HTTP GET metodu ile çağrı UUID'si ve hedef dahili kullanılarak aktarım işlemi gerçekleştirilir. Yeni çağrı başlattığınızda API'den dönen UUID'yi kullanabilirsiniz veya Olay Bildirme ile gelen UUID'leri kullanabilirsiniz.
	//
	// Corresponds with GET /transfer/{id} (the `TransferCall` operationId).
	TransferCall(ctx context.Context, id string, params *TransferCallParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateOutboundCallerId Dahilinin Dış Numarasını (Arayan No) Değiştirme
	//
	// Santralinizdeki dahililerin dış numarasını değiştirmek için kullanılır.
	//
	// HAZIRLIK:
	// Online İşlem Merkezi => Bulut Santralim => Santral Ayarlarım menüsü altından API Anahtarınızı (key) öğrenmelisiniz.
	//
	// ÖNEMLİ NOT:
	// Kullanabileceğiniz numara listesini caller_ids API'sinden öğrenebilirsiniz.
	//
	// Corresponds with GET /update_outbound_caller_id (the `UpdateOutboundCallerId` operationId).
	UpdateOutboundCallerId(ctx context.Context, params *UpdateOutboundCallerIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListUserStatuses Dahili Durumlarını Listeleme
	//
	// Dahililerinizin durumlarını listelemek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/user_statuses adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde mesajlar döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint, /agent_statuses ile aynı hız sınırı havuzunu paylaşır - aynı domain/IP için ikisi birlikte dakikada toplam 2 istek gönderebilirsiniz.
	//
	// Corresponds with GET /user_statuses (the `ListUserStatuses` operationId).
	ListUserStatuses(ctx context.Context, params *ListUserStatusesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVoicemailMessages Telesekreter Arama Kayıtlarına Erişim
	//
	// Santralinizdeki telesekreter arama kayıtlarına ve ses kayıtlarına erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde mesajlar döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Corresponds with GET /voicemail_messages (the `GetVoicemailMessages` operationId).
	GetVoicemailMessages(ctx context.Context, params *GetVoicemailMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateVoicemailRecordingUrl Telesekreter Ses Kaydı için Geçici URL Oluşturma
	//
	// CDR'ın ses kaydına erişimde olduğu gibi, bu ses kayıtlarına erişim de iki aşamalıdır. Birinci aşamada URL elde edilir. İkinci aşamada ise o URL'den ses dosyası indirilir/dinlenir. HTTP POST metodu ile api.bulutsantralim.com adresine parametreler gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde ses kaydına ait olan bir URL döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. URL yaşam süresi 1 saattir.
	//
	// Corresponds with POST /voicemail_recording_url (the `CreateVoicemailRecordingUrl` operationId).
	CreateVoicemailRecordingUrl(ctx context.Context, params *CreateVoicemailRecordingUrlParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WebhookPayloadExamples CRM Webhook Payload Örnekleri
	//
	// CRM entegrasyonu aktif olduğunda gönderilen webhook payload örnekleri. Bu endpoint gerçek bir API değildir, sadece dokümantasyon amaçlıdır.
	//
	// Corresponds with GET /webhook-payload-examples (the `WebhookPayloadExamples` operationId).
	WebhookPayloadExamples(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateWebphoneToken Dahili için Token (Anahtar) Alma (IFrame Gömme için)
	//
	// Web telefonunu kendi uygulamanızda kullanmak için token oluşturur. Her açılışta ilgili dahili için token alınmalıdır. Token 1 gün geçerlidir.
	//
	// Bulut Santral web telefonunu kendi web uygulamanızın içine iframe ile gömmek için kullanılır. Böylece kullanıcılarınız tek pencereyle çalışır ve iki ayrı sisteme login olmak zorunda kalmazlar.
	//
	// Online İşlem Merkezi => Abonelik İşlemleri => Personel Hesapları sayfasında, web telefonunu kullanacak her dahili için bir personel hesabı açıp ilgili dahiliyi seçmiş olmalısınız. Karşılığında personel hesabı olmayan dahililer web telefonunu kullanamaz.
	//
	// Corresponds with POST /webphone_tokens (the `CreateWebphoneToken` operationId).
	CreateWebphoneToken(ctx context.Context, params *CreateWebphoneTokenParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}
