// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import "net/http"

// UpdateOutboundCallerIdParams defines parameters for UpdateOutboundCallerId.
type UpdateOutboundCallerIdParams struct {
	// Extension Dış numarası değiştirilecek olan dahili
	Extension string `form:"extension" json:"extension"`

	// CallerId Dahilinin kullanacağı dış numara. Kullanabileceğiniz numara listesini caller_ids API'sinden öğrenebilirsiniz
	CallerId string `form:"caller_id" json:"caller_id"`
}

type GetCallerIdsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]string
}

type UpdateOutboundCallerIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}
