// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import "net/http"

const (
	GetCrmIntegrations200JSONResponseBodyAnsweredOff GetCrmIntegrations200JSONResponseBodyAnswered = "off"
	GetCrmIntegrations200JSONResponseBodyAnsweredOn  GetCrmIntegrations200JSONResponseBodyAnswered = "on"
)

const (
	GetCrmIntegrations200JSONResponseBodyHangupOff GetCrmIntegrations200JSONResponseBodyHangup = "off"
	GetCrmIntegrations200JSONResponseBodyHangupOn  GetCrmIntegrations200JSONResponseBodyHangup = "on"
)

const (
	GetCrmIntegrations200JSONResponseBodyRingingOff GetCrmIntegrations200JSONResponseBodyRinging = "off"
	GetCrmIntegrations200JSONResponseBodyRingingOn  GetCrmIntegrations200JSONResponseBodyRinging = "on"
)

type GetCrmIntegrations200JSONResponseBodyAnswered string

type GetCrmIntegrations200JSONResponseBodyHangup string

type GetCrmIntegrations200JSONResponseBodyRinging string

type UpdateCrmIntegrationsParams struct {
	Ringing         *string `form:"ringing,omitempty" json:"ringing,omitempty"`
	Answered        *string `form:"answered,omitempty" json:"answered,omitempty"`
	Hangup          *string `form:"hangup,omitempty" json:"hangup,omitempty"`
	NotificationUrl *string `form:"notification_url,omitempty" json:"notification_url,omitempty"`
}
type GetCrmIntegrationsResponse struct {
	Body []byte// Defines values for GetCrmIntegrations200JSONResponseBodyAnswered.
	// NotificationUrl CRM bildirimlerinin gönderileceği webhook URL adresi

	HTTPResponse *http.Response
	JSON200      *struct {
		Answered        GetCrmIntegrations200JSONResponseBodyAnswered `json:"answered"`
		Hangup          GetCrmIntegrations200JSONResponseBodyHangup   `json:"hangup"`
		NotificationUrl string                                        `json:"notification_url"`
		Ringing         GetCrmIntegrations200JSONResponseBodyRinging  `json:"ringing"`
	}
}
type UpdateCrmIntegrationsResponse struct {
	Body []byte// JSON200 the response for an HTTP 200 `application/json` response
	// Ringing Çağrı çalma olayları için webhook bildirimi (on: aktif, off: pasif)

	HTTPResponse *http.Response
}
type WebhookPayloadExamplesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		AnsweredEvent *struct {
			AnswerTime   *string `json:"answer_time,omitempty"`
			CallId       *string `json:"call_id,omitempty"`
			CalledNumber *string `json:"called_number,omitempty"`
			CallerNumber *string `json:"caller_number,omitempty"`
			Event        *string `json:"event,omitempty"`
		} `json:"answered_event,omitempty"`
		HangupEvent *struct {
			CallId       *string `json:"call_id,omitempty"`
			CalledNumber *string `json:"called_number,omitempty"`
			CallerNumber *string `json:"caller_number,omitempty"`
			Duration     *int    `json:"duration,omitempty"`
			Event        *string `json:"event,omitempty"`
			HangupCause  *string `json:"hangup_cause,omitempty"`
		} `json:"hangup_event,omitempty"`
		RingingEvent *struct {
			CallId       *string `json:"call_id,omitempty"`
			CalledNumber *string `json:"called_number,omitempty"`
			CallerNumber *string `json:"caller_number,omitempty"`
			Event        *string `json:"event,omitempty"`
			Timestamp    *string `json:"timestamp,omitempty"`
		} `json:"ringing_event,omitempty"`
	}
}

// JSON200 the response for an HTTP 200 `application/json` response
// RingingEvent Çağrı çalmaya başladığında gönderilen payload
