// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import (
	"context"
	"io"
	"net/http"
)

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListAgentStatusesWithResponse MT Durumlarını ve Üyeliklerini Listeleme
	//
	// Müşteri Temsilcilerinizin durumunu ve hangi kuyruklara üye olduklarını listelemek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/agent_statuses adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde mesajlar döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint, /user_statuses ile aynı hız sınırı havuzunu paylaşır - aynı domain/IP için ikisi birlikte dakikada toplam 2 istek gönderebilirsiniz.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /agent_statuses (the `ListAgentStatuses` operationId).
	ListAgentStatusesWithResponse(ctx context.Context, params *ListAgentStatusesParams, reqEditors ...RequestEditorFn) (*ListAgentStatusesResponse, error)

	// GetAnnouncementsWithResponse Ses Dosyaları Listesine Erişim
	//
	// Santralinizdeki ses dosyalarının listesine erişmek için kullanılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde ses dosyalarının listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /announcements (the `GetAnnouncements` operationId).
	GetAnnouncementsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAnnouncementsResponse, error)

	// CreateAnnouncementWithBodyWithResponse Yeni Ses Dosyası Yükleme
	//
	// Yeni ses dosyası yüklemek için kullanılır. Yeni ses dosyasının ismini ve içeriğinin base64 ile kodlanmış halini POST etmeniz yeterlidir. Başarılı durumda oluşturulan ses dosyasının ID'si döner.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /announcements (the `CreateAnnouncement` operationId).
	CreateAnnouncementWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAnnouncementResponse, error)

	// CreateAnnouncementWithFormdataBodyWithResponse Yeni Ses Dosyası Yükleme
	//
	// Yeni ses dosyası yüklemek için kullanılır. Yeni ses dosyasının ismini ve içeriğinin base64 ile kodlanmış halini POST etmeniz yeterlidir. Başarılı durumda oluşturulan ses dosyasının ID'si döner.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /announcements (the `CreateAnnouncement` operationId).
	CreateAnnouncementWithFormdataBodyWithResponse(ctx context.Context, body CreateAnnouncementFormdataRequestBody, reqEditors ...RequestEditorFn) (*CreateAnnouncementResponse, error)

	// DeleteAnnouncementWithResponse Ses Dosyası Silme
	//
	// Ses dosyasını silmek için kullanılır. Ses dosyasının id ile DELETE etmeniz yeterlidir. Başarılı durumda OK döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /announcements/{id} (the `DeleteAnnouncement` operationId).
	DeleteAnnouncementWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteAnnouncementResponse, error)

	// UpdateAnnouncementWithBodyWithResponse Ses Dosyası Güncelleme
	//
	// Mevcut ses dosyasının adını ve içeriğini güncellemek için kullanılır. Ses dosyasının ismini ve içeriğinin base64 ile kodlanmış halini PATCH etmeniz yeterlidir. Başarılı durumda OK döner.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /announcements/{id} (the `UpdateAnnouncement` operationId).
	UpdateAnnouncementWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAnnouncementResponse, error)

	// UpdateAnnouncementWithFormdataBodyWithResponse Ses Dosyası Güncelleme
	//
	// Mevcut ses dosyasının adını ve içeriğini güncellemek için kullanılır. Ses dosyasının ismini ve içeriğinin base64 ile kodlanmış halini PATCH etmeniz yeterlidir. Başarılı durumda OK döner.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /announcements/{id} (the `UpdateAnnouncement` operationId).
	UpdateAnnouncementWithFormdataBodyWithResponse(ctx context.Context, id string, body UpdateAnnouncementFormdataRequestBody, reqEditors ...RequestEditorFn) (*UpdateAnnouncementResponse, error)

	// AnswerCallPostWithBodyWithResponse Çağrıyı Cevaplama (POST)
	//
	// manual_answer=true parametresi ile başlatılmış bir çağrıyı cevaplamak için HTTP POST metodu ile /answer endpoint'i id parametresi ile çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 döner.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /answer (the `AnswerCallPost` operationId).
	AnswerCallPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AnswerCallPostResponse, error)

	// AnswerCallPostWithResponse Çağrıyı Cevaplama (POST)
	//
	// manual_answer=true parametresi ile başlatılmış bir çağrıyı cevaplamak için HTTP POST metodu ile /answer endpoint'i id parametresi ile çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 döner.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /answer (the `AnswerCallPost` operationId).
	AnswerCallPostWithResponse(ctx context.Context, body AnswerCallPostJSONRequestBody, reqEditors ...RequestEditorFn) (*AnswerCallPostResponse, error)

	// AnswerCallPostWithFormdataBodyWithResponse Çağrıyı Cevaplama (POST)
	//
	// manual_answer=true parametresi ile başlatılmış bir çağrıyı cevaplamak için HTTP POST metodu ile /answer endpoint'i id parametresi ile çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 döner.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /answer (the `AnswerCallPost` operationId).
	AnswerCallPostWithFormdataBodyWithResponse(ctx context.Context, body AnswerCallPostFormdataRequestBody, reqEditors ...RequestEditorFn) (*AnswerCallPostResponse, error)

	// AnswerCallWithResponse Çağrıyı Cevaplama (GET)
	//
	// manual_answer=true parametresi ile başlatılmış ve dahili telefonda çalmakta olan bir çağrıyı API üzerinden cevaplamak için kullanılır. HTTP GET metodu ile /answer/{id} çağrılır. Başarılı olduğunda çağrı cevaplanır ve HTTP 200 ile +OK veya çağrıya ilişkin bilgi döner. Başarısız olduğunda ilgili hata mesajı body'de döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /answer/{id} (the `AnswerCall` operationId).
	AnswerCallWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*AnswerCallResponse, error)

	// ListBlockedNumbersWithResponse Kara Listeye Erişim
	//
	// Santralinizdeki kara listedeki numaraların listesine erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/blocked_numbers adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde kara liste döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /blocked_numbers (the `ListBlockedNumbers` operationId).
	ListBlockedNumbersWithResponse(ctx context.Context, params *ListBlockedNumbersParams, reqEditors ...RequestEditorFn) (*ListBlockedNumbersResponse, error)

	// CreateBlockedNumberWithResponse Kara Listeye Ekleme
	//
	// Telefon numarasını kara listeye ekler. Numara kayıt edilmeden önce normalize edilir. POST metodu ile api.bulutsantralim.com/blocked_numbers adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde oluşturulan kaydın ID'si döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /blocked_numbers (the `CreateBlockedNumber` operationId).
	CreateBlockedNumberWithResponse(ctx context.Context, params *CreateBlockedNumberParams, reqEditors ...RequestEditorFn) (*CreateBlockedNumberResponse, error)

	// DeleteBlockedNumberWithResponse Kara Listeden Silme
	//
	// Telefon numarasını kara listeden çıkarır. Numara kaldırılmadan önce normalize edilir. DELETE metodu ile api.bulutsantralim.com/blocked_numbers/delete adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde başarı mesajı döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /blocked_numbers/delete (the `DeleteBlockedNumber` operationId).
	DeleteBlockedNumberWithResponse(ctx context.Context, params *DeleteBlockedNumberParams, reqEditors ...RequestEditorFn) (*DeleteBlockedNumberResponse, error)

	// CreateBridgeWithResponse Çağrı Bağlama
	//
	// Uygulamalarınız üzerinden iki dış numarayı (örn. cep telefonu) arayıp birbiriyle görüştürmek için kullanılır. Kullanım alanları: Müşteriniz ve saha personelinizi görüştürmek istiyorsunuz fakat bilgi güvenliği (örn. KVKK) nedeniyle cep telefonu numaralarının görünmesini istemiyorsunuz (numara maskeleme/gizleme). Müşteriniz ve saha personelinizin yaptığı görüşmeleri raporlamak ve ses kayıtlarını tutmak istiyorsunuz. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /bridge (the `CreateBridge` operationId).
	CreateBridgeWithResponse(ctx context.Context, params *CreateBridgeParams, reqEditors ...RequestEditorFn) (*CreateBridgeResponse, error)

	// GetCallerIdsWithResponse Dış Numaralar Listesine Erişim
	//
	// Santralinizdeki Arayan Numara olarak kullanabileceğiniz numaraların listesine erişmek için kullanılır.
	//
	// HAZIRLIK:
	// Online İşlem Merkezi => Bulut Santralim => Santral Ayarlarım menüsü altından API Anahtarınızı (key) öğrenmelisiniz.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /caller_ids (the `GetCallerIds` operationId).
	GetCallerIdsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCallerIdsResponse, error)

	// GetCdrsWithResponse Çağrı Detay Kayıtları (CDR) Listesi
	//
	// Farklı filtrelerle ve sayfalama ile çağrı detay kayıtlarını (CDR) listeler. Bu endpoint dakikada en fazla 6 istek ile sınırlıdır.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /cdrs (the `GetCdrs` operationId).
	GetCdrsWithResponse(ctx context.Context, params *GetCdrsParams, reqEditors ...RequestEditorFn) (*GetCdrsResponse, error)

	// GetCdrWithResponse Belirli Bir Çağrının Detaylı CDR Kaydı
	//
	// Belirli bir çağrıya ait tüm detayları ve çağrı akışını getirir. Bu endpoint dakikada en fazla 6 istek ile sınırlıdır.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /cdrs/{id} (the `GetCdr` operationId).
	GetCdrWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetCdrResponse, error)

	// ListContactGroupsWithResponse Grup Listesine Erişim
	//
	// Santralinizdeki kişi gruplarının listesine erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/contact_groups adresi çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde gruplar listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /contact_groups (the `ListContactGroups` operationId).
	ListContactGroupsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListContactGroupsResponse, error)

	// CreateContactGroupWithResponse Grup Oluşturma
	//
	// Yeni bir kişi grubu oluşturur. Google Kişiler entegrasyonunun kapalı olması gerekir. POST metodu ile api.bulutsantralim.com/contact_groups adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde oluşturulan grubun ID'si döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /contact_groups (the `CreateContactGroup` operationId).
	CreateContactGroupWithResponse(ctx context.Context, params *CreateContactGroupParams, reqEditors ...RequestEditorFn) (*CreateContactGroupResponse, error)

	// DeleteContactGroupWithResponse Grup Silme
	//
	// Mevcut bir kişi grubunu siler. Google Kişiler entegrasyonunun kapalı olması gerekir. DELETE metodu ile api.bulutsantralim.com/contact_groups/{id} adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /contact_groups/{id} (the `DeleteContactGroup` operationId).
	DeleteContactGroupWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteContactGroupResponse, error)

	// UpdateContactGroupWithResponse Grup Güncelleme
	//
	// Mevcut bir kişi grubunu günceller. Google Kişiler entegrasyonunun kapalı olması gerekir. PATCH metodu ile api.bulutsantralim.com/contact_groups/{id} adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /contact_groups/{id} (the `UpdateContactGroup` operationId).
	UpdateContactGroupWithResponse(ctx context.Context, id int, params *UpdateContactGroupParams, reqEditors ...RequestEditorFn) (*UpdateContactGroupResponse, error)

	// ListContactsWithResponse Kişiler Listesine Erişim
	//
	// Santralinizdeki kişiler listesine erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/contacts adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde kişiler listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /contacts (the `ListContacts` operationId).
	ListContactsWithResponse(ctx context.Context, params *ListContactsParams, reqEditors ...RequestEditorFn) (*ListContactsResponse, error)

	// CreateContactWithResponse Kişi Ekleme
	//
	// Yeni bir kişi oluşturur. Google Kişiler entegrasyonunun kapalı olması gerekir. POST metodu ile api.bulutsantralim.com/contacts adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde oluşturulan kişinin ID'si döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /contacts (the `CreateContact` operationId).
	CreateContactWithResponse(ctx context.Context, params *CreateContactParams, reqEditors ...RequestEditorFn) (*CreateContactResponse, error)

	// DeleteContactWithResponse Kişi Silme
	//
	// Mevcut bir kişiyi siler. Google Kişiler entegrasyonunun kapalı olması gerekir. DELETE metodu ile api.bulutsantralim.com/contacts/{id} adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /contacts/{id} (the `DeleteContact` operationId).
	DeleteContactWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteContactResponse, error)

	// UpdateContactWithResponse Kişi Güncelleme
	//
	// Mevcut bir kişiyi günceller. Google Kişiler entegrasyonunun kapalı olması gerekir. Kişi eklerken kullanabileceğiniz tüm parametreler güncelleme için de geçerlidir. PATCH metodu ile api.bulutsantralim.com/contacts/{id} adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /contacts/{id} (the `UpdateContact` operationId).
	UpdateContactWithResponse(ctx context.Context, id int, params *UpdateContactParams, reqEditors ...RequestEditorFn) (*UpdateContactResponse, error)

	// GetCrmIntegrationsWithResponse CRM Entegrasyon Ayarlarını Getirme
	//
	// Çağrı olayları (çalma, cevaplanma, kapanma) için mevcut CRM webhook entegrasyon ayarlarını getirir. Bu endpoint ile hangi olaylar için webhook bildirimleri aktif olduğunu ve webhook URL'ini öğrenebilirsiniz.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /crm_integrations (the `GetCrmIntegrations` operationId).
	GetCrmIntegrationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCrmIntegrationsResponse, error)

	// UpdateCrmIntegrationsWithResponse CRM Entegrasyon Ayarlarını Güncelleme
	//
	// Çağrı olayları için CRM webhook entegrasyon ayarlarını günceller. Çalma, cevaplanma ve kapanma olayları için bildirimleri etkinleştirir veya devre dışı bırakır. Webhook URL'i de güncellenebilir.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /crm_integrations (the `UpdateCrmIntegrations` operationId).
	UpdateCrmIntegrationsWithResponse(ctx context.Context, params *UpdateCrmIntegrationsParams, reqEditors ...RequestEditorFn) (*UpdateCrmIntegrationsResponse, error)

	// CreateDndWithResponse Dahili için Rahatsız Etme (DND) Modunu Ayarlama
	//
	// Kullanıcının dahili numarası için Rahatsız Etme (DND) modunu açar veya kapatır. DND açıkken kullanıcıya gelen çağrılar engellenir.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /dnd/{id} (the `CreateDnd` operationId).
	CreateDndWithResponse(ctx context.Context, id string, params *CreateDndParams, reqEditors ...RequestEditorFn) (*CreateDndResponse, error)

	// ListExtensionsWithResponse Dahili Listesi
	//
	// Santralinizdeki tüm dahilileri listelemek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/extensions adresi çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde dahili listesi döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /extensions (the `ListExtensions` operationId).
	ListExtensionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListExtensionsResponse, error)

	// GetExtensionWithResponse Dahili Detayı
	//
	// Belirli bir dahilinin detaylarını getirmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/extensions/{id} adresi çağrılır.
	//
	// ÖNEMLİ NOT:
	// Yanıt, dahilinin SIP şifresini (`password`) düz metin olarak içerir. Bu yanıtı güvenli şekilde saklayın ve loglamayın.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /extensions/{id} (the `GetExtension` operationId).
	GetExtensionWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetExtensionResponse, error)

	// DownloadFaxDocumentWithResponse Faks Belgesi İndirme/Görüntüleme
	//
	// Bu servis, daha önce 'Faks Belgesi URL'si İsteme' ile elde edilen geçici URL üzerinden faks belgesini indirmenizi veya görüntülemenizi sağlar.
	//
	// URL, 1 saat geçerlidir. Herhangi bir kimlik doğrulama gerekmez; güvenlik, URL'nin kendisinde bulunan tek kullanımlık ticket kodu ile sağlanır.
	//
	// Başarılı isteklerde HTTP 200 ile belge dosyası (PDF/TIFF) döner. Hatalı veya süresi dolmuş ticket ile yapılan isteklerde uygun hata mesajı ve HTTP 400 döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /fax_document/{id} (the `DownloadFaxDocument` operationId).
	DownloadFaxDocumentWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DownloadFaxDocumentResponse, error)

	// CreateFaxDocumentUrlWithResponse Faks Belgesi URL'si İsteme
	//
	// Başarıyla iletilen faks belgesi için geçici indirme URL'si oluşturur. HTTP POST metodu ile api.bulutsantralim.com/fax_document_url/ adresine istek gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde belgeye ait URL döner. URL yaşam süresi 1 saattir ve PDF versiyonuna erişim sağlar. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /fax_document_url (the `CreateFaxDocumentUrl` operationId).
	CreateFaxDocumentUrlWithResponse(ctx context.Context, params *CreateFaxDocumentUrlParams, reqEditors ...RequestEditorFn) (*CreateFaxDocumentUrlResponse, error)

	// ListFaxOrdersWithResponse Tamamlanmamış Faks Gönderimlerinin Listesi
	//
	// Santraldaki tamamlanmamış faks gönderimlerinin listesine erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/fax_orders adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde faks gönderim kayıtları döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /fax_orders (the `ListFaxOrders` operationId).
	ListFaxOrdersWithResponse(ctx context.Context, params *ListFaxOrdersParams, reqEditors ...RequestEditorFn) (*ListFaxOrdersResponse, error)

	// CreateFaxOrderWithResponse Faks Gönderimi
	//
	// Faks göndermek için dosyasının içeriğinin base64 ile kodlanmış halini ve diğer bilgileri POST etmeniz yeterlidir. Uygulamalarınız üzerinden faks göndermek için api.bulutsantralim.com/fax_orders adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 status kodu ile mesajın Body'sinde faks ID döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /fax_orders (the `CreateFaxOrder` operationId).
	CreateFaxOrderWithResponse(ctx context.Context, params *CreateFaxOrderParams, reqEditors ...RequestEditorFn) (*CreateFaxOrderResponse, error)

	// ListFdrsWithResponse Faks Listesine Erişim
	//
	// Santralinizdeki faks detay kayıtlarının listesine erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/fdrs adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde faks kayıtları döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Tarih aralığı 31 günden uzun olamaz.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /fdrs (the `ListFdrs` operationId).
	ListFdrsWithResponse(ctx context.Context, params *ListFdrsParams, reqEditors ...RequestEditorFn) (*ListFdrsResponse, error)

	// HangupCallWithResponse Çağrıyı Sonlandırma
	//
	// Uygulamalarınız üzerinden santralde devam eden bir çağrıyı sonlandırmak için kullanılır. HTTP GET metodu ile api.bulutsantralim.com adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde +OK döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hangup/{id} (the `HangupCall` operationId).
	HangupCallWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*HangupCallResponse, error)

	// CreateIvrCampaignWithBodyWithResponse Otomatik Arama Kampanyası Oluşturma
	//
	// Yeni otomatik arama kampanyası oluşturmak için kullanılır. JSON formatında parametreler ile POST isteği gönderilir. ivr_campaigns endpoint'leri saniyede 2 istek (yaklaşık dakikada 120) limitine tabidir, burst değeri 50'dir.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /ivr_campaigns.json (the `CreateIvrCampaign` operationId).
	CreateIvrCampaignWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateIvrCampaignResponse, error)

	// CreateIvrCampaignWithResponse Otomatik Arama Kampanyası Oluşturma
	//
	// Yeni otomatik arama kampanyası oluşturmak için kullanılır. JSON formatında parametreler ile POST isteği gönderilir. ivr_campaigns endpoint'leri saniyede 2 istek (yaklaşık dakikada 120) limitine tabidir, burst değeri 50'dir.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /ivr_campaigns.json (the `CreateIvrCampaign` operationId).
	CreateIvrCampaignWithResponse(ctx context.Context, body CreateIvrCampaignJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateIvrCampaignResponse, error)

	// DeleteIvrCampaignWithResponse Otomatik Arama Kampanyasını Silme
	//
	// Otomatik arama kampanyasını iptal etmek/silmek için kullanılır. Kampanya ID'si ve API anahtarı ile DELETE isteği gönderilir.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /ivr_campaigns/{id}.json (the `DeleteIvrCampaign` operationId).
	DeleteIvrCampaignWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteIvrCampaignResponse, error)

	// UpdateIvrCampaignWithResponse Otomatik Arama Kampanyasını Başlatma/Durdurma
	//
	// Otomatik arama kampanyasını durdurmak veya tekrar başlatmak için kullanılır. PATCH ile status=off gönderilirse kampanya durur, status=on gönderilirse tekrar başlar.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /ivr_campaigns/{id}.json (the `UpdateIvrCampaign` operationId).
	UpdateIvrCampaignWithResponse(ctx context.Context, id string, params *UpdateIvrCampaignParams, reqEditors ...RequestEditorFn) (*UpdateIvrCampaignResponse, error)

	// MuteCallWithResponse Çağrıyı Sessize Alma / Sesli Yapma
	//
	// Santralde devam eden bir çağrıyı sessize almak veya sesli yapmak için kullanılır. HTTP GET metodu ile çağrı UUID'si ve state parametresi kullanılarak mute işlemi gerçekleştirilir.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /mute/{id} (the `MuteCall` operationId).
	MuteCallWithResponse(ctx context.Context, id string, params *MuteCallParams, reqEditors ...RequestEditorFn) (*MuteCallResponse, error)

	// OriginateCallWithResponse Çağrı Başlatma (GET)
	//
	// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
	//
	// HAZIRLIK:
	// Online İşlem Merkezi => Bulut Santralim => Santral Ayarlarım menüsü altından API Anahtarınızı (key) öğrenmelisiniz.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /originate (the `OriginateCall` operationId).
	OriginateCallWithResponse(ctx context.Context, params *OriginateCallParams, reqEditors ...RequestEditorFn) (*OriginateCallResponse, error)

	// OriginateCallPostWithBodyWithResponse Çağrı Başlatma (POST)
	//
	// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP POST metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /originate (the `OriginateCallPost` operationId).
	OriginateCallPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OriginateCallPostResponse, error)

	// OriginateCallPostWithResponse Çağrı Başlatma (POST)
	//
	// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP POST metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /originate (the `OriginateCallPost` operationId).
	OriginateCallPostWithResponse(ctx context.Context, body OriginateCallPostJSONRequestBody, reqEditors ...RequestEditorFn) (*OriginateCallPostResponse, error)

	// OriginateCallPostWithFormdataBodyWithResponse Çağrı Başlatma (POST)
	//
	// Uygulamalarınız üzerinden santraldeki bir dahiliye çağrı başlatmak için kullanılır. Bunun için HTTP POST metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde call_uuid döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint saniyede 3 istek (yaklaşık dakikada 180) limitine tabidir, burst değeri 100'dür.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /originate (the `OriginateCallPost` operationId).
	OriginateCallPostWithFormdataBodyWithResponse(ctx context.Context, body OriginateCallPostFormdataRequestBody, reqEditors ...RequestEditorFn) (*OriginateCallPostResponse, error)

	// ManageQueueUsersWithResponse Kuyruğa Dahili Ekleme, Çıkarma veya Yer Değiştirme
	//
	// Santralinizdeki kuyruklara dahili ekleme, çıkarma veya yer değiştirme için kullanılır. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde OK döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /queue/manage_users (the `ManageQueueUsers` operationId).
	ManageQueueUsersWithResponse(ctx context.Context, params *ManageQueueUsersParams, reqEditors ...RequestEditorFn) (*ManageQueueUsersResponse, error)

	// GetQueueUserListWithResponse Kuyruktaki Dahili Listesine Erişim
	//
	// Santralinizdeki kuyruğun dahili sırasını listeler. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde dahili listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /queue/user_list (the `GetQueueUserList` operationId).
	GetQueueUserListWithResponse(ctx context.Context, params *GetQueueUserListParams, reqEditors ...RequestEditorFn) (*GetQueueUserListResponse, error)

	// GetQueuesWithResponse Kuyruklar Listesine Erişim
	//
	// Santralinizdeki kuyrukların listesine erişmek için kullanılır. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde kuyrukların listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /queues (the `GetQueues` operationId).
	GetQueuesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetQueuesResponse, error)

	// GetQueuesPendingWithResponse Kuyrukta Bekleyenler Listesine Erişim
	//
	// Santralinizdeki kuyrukta bekleyenlerin listesine erişmek için kullanılır. Bunun için HTTP GET metodu ile api.bulutsantralim.com adresi aşağıdaki parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde kuyrukta bekleyenlerin listesi döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint dakikada en fazla 10 istek ile sınırlıdır.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /queues/pending (the `GetQueuesPending` operationId).
	GetQueuesPendingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetQueuesPendingResponse, error)

	// CreateRecordingUrlWithResponse Ses Kaydı için Geçici URL Oluşturma
	//
	// Santralinizdeki veya Google Drive'a aktarılmış ses kayıtlarınıza erişmek için geçici bir URL oluşturur. URL 1 saat geçerlidir ve dakikada en fazla 5 istek yapılabilir.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /recording_url (the `CreateRecordingUrl` operationId).
	CreateRecordingUrlWithResponse(ctx context.Context, params *CreateRecordingUrlParams, reqEditors ...RequestEditorFn) (*CreateRecordingUrlResponse, error)

	// TransferCallPostWithResponse Çağrıyı Aktarma (POST)
	//
	// Santralde devam eden bir çağrıyı başka bir dahiliye aktarmak için kullanılır. POST metodu ile çağrı UUID'si ve hedef dahili kullanılarak aktarım işlemi gerçekleştirilir.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /transfer (the `TransferCallPost` operationId).
	TransferCallPostWithResponse(ctx context.Context, params *TransferCallPostParams, reqEditors ...RequestEditorFn) (*TransferCallPostResponse, error)

	// TransferCallWithResponse Çağrıyı Aktarma (GET)
	//
	// Santralde devam eden bir çağrıyı aktarmak için kullanılır. HTTP GET metodu ile çağrı UUID'si ve hedef dahili kullanılarak aktarım işlemi gerçekleştirilir. Yeni çağrı başlattığınızda API'den dönen UUID'yi kullanabilirsiniz veya Olay Bildirme ile gelen UUID'leri kullanabilirsiniz.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /transfer/{id} (the `TransferCall` operationId).
	TransferCallWithResponse(ctx context.Context, id string, params *TransferCallParams, reqEditors ...RequestEditorFn) (*TransferCallResponse, error)

	// UpdateOutboundCallerIdWithResponse Dahilinin Dış Numarasını (Arayan No) Değiştirme
	//
	// Santralinizdeki dahililerin dış numarasını değiştirmek için kullanılır.
	//
	// HAZIRLIK:
	// Online İşlem Merkezi => Bulut Santralim => Santral Ayarlarım menüsü altından API Anahtarınızı (key) öğrenmelisiniz.
	//
	// ÖNEMLİ NOT:
	// Kullanabileceğiniz numara listesini caller_ids API'sinden öğrenebilirsiniz.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /update_outbound_caller_id (the `UpdateOutboundCallerId` operationId).
	UpdateOutboundCallerIdWithResponse(ctx context.Context, params *UpdateOutboundCallerIdParams, reqEditors ...RequestEditorFn) (*UpdateOutboundCallerIdResponse, error)

	// ListUserStatusesWithResponse Dahili Durumlarını Listeleme
	//
	// Dahililerinizin durumlarını listelemek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com/user_statuses adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde mesajlar döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. Bu endpoint, /agent_statuses ile aynı hız sınırı havuzunu paylaşır - aynı domain/IP için ikisi birlikte dakikada toplam 2 istek gönderebilirsiniz.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /user_statuses (the `ListUserStatuses` operationId).
	ListUserStatusesWithResponse(ctx context.Context, params *ListUserStatusesParams, reqEditors ...RequestEditorFn) (*ListUserStatusesResponse, error)

	// GetVoicemailMessagesWithResponse Telesekreter Arama Kayıtlarına Erişim
	//
	// Santralinizdeki telesekreter arama kayıtlarına ve ses kayıtlarına erişmek için kullanılır. HTTP GET metodu ile api.bulutsantralim.com adresi parametrelerle çağrılır. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde mesajlar döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /voicemail_messages (the `GetVoicemailMessages` operationId).
	GetVoicemailMessagesWithResponse(ctx context.Context, params *GetVoicemailMessagesParams, reqEditors ...RequestEditorFn) (*GetVoicemailMessagesResponse, error)

	// CreateVoicemailRecordingUrlWithResponse Telesekreter Ses Kaydı için Geçici URL Oluşturma
	//
	// CDR'ın ses kaydına erişimde olduğu gibi, bu ses kayıtlarına erişim de iki aşamalıdır. Birinci aşamada URL elde edilir. İkinci aşamada ise o URL'den ses dosyası indirilir/dinlenir. HTTP POST metodu ile api.bulutsantralim.com adresine parametreler gönderilir. İstek başarılı olduğunda HTTP 200 Status kodu ile mesajın Body'sinde ses kaydına ait olan bir URL döner. İstek başarısız olduğunda ise ilgili HTTP Status kodu ile mesajın Body'sinde hata mesajı döner. URL yaşam süresi 1 saattir.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /voicemail_recording_url (the `CreateVoicemailRecordingUrl` operationId).
	CreateVoicemailRecordingUrlWithResponse(ctx context.Context, params *CreateVoicemailRecordingUrlParams, reqEditors ...RequestEditorFn) (*CreateVoicemailRecordingUrlResponse, error)

	// WebhookPayloadExamplesWithResponse CRM Webhook Payload Örnekleri
	//
	// CRM entegrasyonu aktif olduğunda gönderilen webhook payload örnekleri. Bu endpoint gerçek bir API değildir, sadece dokümantasyon amaçlıdır.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /webhook-payload-examples (the `WebhookPayloadExamples` operationId).
	WebhookPayloadExamplesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*WebhookPayloadExamplesResponse, error)

	// CreateWebphoneTokenWithResponse Dahili için Token (Anahtar) Alma (IFrame Gömme için)
	//
	// Web telefonunu kendi uygulamanızda kullanmak için token oluşturur. Her açılışta ilgili dahili için token alınmalıdır. Token 1 gün geçerlidir.
	//
	// Bulut Santral web telefonunu kendi web uygulamanızın içine iframe ile gömmek için kullanılır. Böylece kullanıcılarınız tek pencereyle çalışır ve iki ayrı sisteme login olmak zorunda kalmazlar.
	//
	// Online İşlem Merkezi => Abonelik İşlemleri => Personel Hesapları sayfasında, web telefonunu kullanacak her dahili için bir personel hesabı açıp ilgili dahiliyi seçmiş olmalısınız. Karşılığında personel hesabı olmayan dahililer web telefonunu kullanamaz.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /webphone_tokens (the `CreateWebphoneToken` operationId).
	CreateWebphoneTokenWithResponse(ctx context.Context, params *CreateWebphoneTokenParams, reqEditors ...RequestEditorFn) (*CreateWebphoneTokenResponse, error)
}

// WebhookInitiator sends OpenAPI 3.1 webhook requests to target URLs.
// Modeled on the generated Client, but with no stored Server -- the full
// target URL is provided per-call by the caller (typically discovered
// from a subscription registration).
type WebhookInitiator struct {
	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// WebhookInitiatorOption allows setting custom parameters during construction.
type WebhookInitiatorOption func(*WebhookInitiator) error

// WebhookInitiatorInterface is the interface specification for the webhook initiator.
type WebhookInitiatorInterface interface {
	// IVRKampanyaRaporAlimiWithBody fires the IVRKampanyaRaporAlimi webhook with any body
	IVRKampanyaRaporAlimiWithBody(ctx context.Context, targetURL string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	IVRKampanyaRaporAlimiWithFormdataBody(ctx context.Context, targetURL string, body IVRKampanyaRaporAlimiFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OlayBildirmeWithBody fires the olayBildirme webhook with any body
	OlayBildirmeWithBody(ctx context.Context, targetURL string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OlayBildirmeWithFormdataBody(ctx context.Context, targetURL string, body OlayBildirmeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}
