// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import "net/http"

type ManageQueueUsersParams struct {
	QueueNumber string `form:"queue_number" json:"queue_number"`
	UserList    string `form:"user_list" json:"user_list"`
}

type GetQueueUserListParams struct {
	QueueNumber string `form:"queue_number" json:"queue_number"`
}
type ManageQueueUsersResponse struct {
	Body []byte// ManageQueueUsersParams defines parameters for ManageQueueUsers.
	// QueueNumber Kuyruk numarası

	HTTPResponse *http.Response
}
type GetQueueUserListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]struct// JSON200 the response for an HTTP 200 `application/json` response
	{
		Name *string `json:"name,omitempty"`
		User *int    `json:"user,omitempty"`
	}
}
type GetQueuesResponse struct {
	Body []byte// Name Dahili adı
	// User Dahili numarası

	HTTPResponse *http.Response
	JSON200      *[]struct// JSON200 the response for an HTTP 200 `application/json` response
	{
		Name   *string `json:"name,omitempty"`
		Number *int    `json:"number,omitempty"`
	}
}
type GetQueuesPendingResponse struct {
	Body []byte// Name Kuyruk adı
	// Number Kuyruk numarası

	HTTPResponse *http.Response
	JSON200      *[]struct// JSON200 the response for an HTTP 200 `application/json` response
	{
		CallUuid    *string `json:"call_uuid,omitempty"`
		CallerId    *string `json:"caller_id,omitempty"`
		JoinedAt    *string `json:"joined_at,omitempty"`
		QueueNumber *string `json:"queue_number,omitempty"`
		Uuid        *string `json:"uuid,omitempty"`
		WaitTime    *int    `json:"wait_time,omitempty"`
	}
}

// CallUuid Çağrı UUID'si
// WaitTime Bekleme süresi (saniye)
