// Package verimorswitch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorswitch

import (
	"net/http"
	"time"
)

type CreateFaxDocumentUrlParams struct {
	CallUuid string `form:"call_uuid" json:"call_uuid"`
}

type ListFaxOrdersParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

type CreateFaxOrderParams struct {
	LocalStationId     *string `form:"local_station_id,omitempty" json:"local_station_id,omitempty"`
	LocalStationHeader *string `form:"local_station_header,omitempty" json:"local_station_header,omitempty"`
	RemoteStationId    string  `form:"remote_station_id" json:"remote_station_id"`
	Filedata           string  `form:"filedata" json:"filedata"`
}

type ListFdrsParams struct {
	StartStampFrom      *string `form:"start_stamp_from,omitempty" json:"start_stamp_from,omitempty"`
	StartStampTo        *string `form:"start_stamp_to,omitempty" json:"start_stamp_to,omitempty"`
	Direction           *string `form:"direction,omitempty" json:"direction,omitempty"`
	CallerIdNumber      *string `form:"caller_id_number,omitempty" json:"caller_id_number,omitempty"`
	OriginalDestination *string `form:"original_destination,omitempty" json:"original_destination,omitempty"`
	Success             *string `form:"success,omitempty" json:"success,omitempty"`
	Page                *int    `form:"page,omitempty" json:"page,omitempty"`
	Limit               *int    `form:"limit,omitempty" json:"limit,omitempty"`
}
type DownloadFaxDocumentResponse struct {
	Body []byte// CreateFaxDocumentUrlParams defines parameters for CreateFaxDocumentUrl.
	// Limit Listeyi sınırlayabilirsiniz. Varsayılan değer 10, minimum değer 10, maksimum değer 100

	HTTPResponse *http.Response
}
type CreateFaxDocumentUrlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}
type ListFaxOrdersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		FaxOrders []struct// JSON200 the response for an HTTP 200 `application/json` response
		{
			CreatedAt       time.Time `json:"created_at"`
			Id              int       `json:"id"`
			LocalStationId  string    `json:"local_station_id"`
			RemoteStationId string    `json:"remote_station_id"`
			Status          string    `json:"status"`
		} `json:"fax_orders"`
		Pagination struct {
			Limit      int `json:"limit"`
			Page       int `json:"page"`
			TotalCount int `json:"total_count"`
			TotalPages int `json:"total_pages"`
		} `json:"pagination"`
	}
}
type CreateFaxOrderResponse struct {
	Body []byte// CreatedAt Kayıt zamanı
	// TotalPages Toplam sayfa sayısı

	HTTPResponse *http.Response
}
type ListFdrsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Fdrs []struct// JSON200 the response for an HTTP 200 `application/json` response
		{
			AnswerStamp         *time.Time `json:"answer_stamp,omitempty"`
			CallUuid            string     `json:"call_uuid"`
			CallerIdNumber      string     `json:"caller_id_number"`
			Direction           string     `json:"direction"`
			Duration            *int       `json:"duration,omitempty"`
			EndStamp            *time.Time `json:"end_stamp,omitempty"`
			LocalStationHeader  *string    `json:"local_station_header,omitempty"`
			OriginalDestination string     `json:"original_destination"`
			PagesCount          string     `json:"pages_count"`
			Result              string     `json:"result"`
			StartStamp          time.Time  `json:"start_stamp"`
			Success             bool       `json:"success"`
			TransferRate        *int       `json:"transfer_rate,omitempty"`
		} `json:"fdrs"`
		Pagination struct {
			Limit      int `json:"limit"`
			Page       int `json:"page"`
			TotalCount int `json:"total_count"`
			TotalPages int `json:"total_pages"`
		} `json:"pagination"`
	}
}

// AnswerStamp Cevaplama Zamanı
// TotalPages Toplam sayfa sayısı
