# Code generated by scripts/facades.py. DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping

from verimor._core import AsyncClientBase, SyncClientBase

_OPERATIONS: dict[str, dict[str, object]] = {
    "post_v2_blacklists": {
        "bodyRequired": False,
        "bodyRequiredFields": [],
        "clientDefaults": {},
        "contentType": None,
        "credentials": {"password": "query", "username": "query"},
        "hasBody": False,
        "method": "POST",
        "operationId": "post_v2_blacklists",
        "parameters": [
            {"location": "query", "publicName": "phones", "required": True, "wireName": "phones"}
        ],
        "path": "/v2/blacklists",
        "responseKind": "text",
    },
    "get_v2_balance": {
        "bodyRequired": False,
        "bodyRequiredFields": [],
        "clientDefaults": {},
        "contentType": None,
        "credentials": {"password": "query", "username": "query"},
        "hasBody": False,
        "method": "GET",
        "operationId": "get_v2_balance",
        "parameters": [],
        "path": "/v2/balance",
        "responseKind": "text",
    },
    "post_v2_cancel_id": {
        "bodyRequired": False,
        "bodyRequiredFields": ["username", "password"],
        "clientDefaults": {},
        "contentType": "application/json",
        "credentials": {"password": "body", "username": "body"},
        "hasBody": True,
        "method": "POST",
        "operationId": "post_v2_cancel_id",
        "parameters": [
            {"location": "path", "publicName": "id", "required": True, "wireName": "id"}
        ],
        "path": "/v2/cancel/{id}",
        "responseKind": "text",
    },
    "delete_v2_blacklists_id": {
        "bodyRequired": False,
        "bodyRequiredFields": [],
        "clientDefaults": {},
        "contentType": None,
        "credentials": {"password": "query", "username": "query"},
        "hasBody": False,
        "method": "DELETE",
        "operationId": "delete_v2_blacklists_id",
        "parameters": [
            {"location": "path", "publicName": "id", "required": True, "wireName": "id"}
        ],
        "path": "/v2/blacklists/{id}",
        "responseKind": "text",
    },
    "get_v2_blacklists": {
        "bodyRequired": False,
        "bodyRequiredFields": [],
        "clientDefaults": {},
        "contentType": None,
        "credentials": {"password": "query", "username": "query"},
        "hasBody": False,
        "method": "GET",
        "operationId": "get_v2_blacklists",
        "parameters": [
            {"location": "query", "publicName": "offset", "required": False, "wireName": "offset"},
            {"location": "query", "publicName": "limit", "required": False, "wireName": "limit"},
        ],
        "path": "/v2/blacklists",
        "responseKind": "json",
    },
    "get_v2_inbound_messages": {
        "bodyRequired": False,
        "bodyRequiredFields": [],
        "clientDefaults": {},
        "contentType": None,
        "credentials": {"password": "query", "username": "query"},
        "hasBody": False,
        "method": "GET",
        "operationId": "get_v2_inbound_messages",
        "parameters": [
            {
                "location": "query",
                "publicName": "fromTime",
                "required": False,
                "wireName": "from_time",
            },
            {"location": "query", "publicName": "toTime", "required": False, "wireName": "to_time"},
            {
                "location": "query",
                "publicName": "greaterThan",
                "required": False,
                "wireName": "greater_than",
            },
        ],
        "path": "/v2/inbound_messages",
        "responseKind": "json",
    },
    "get_v2_iys_campaigns_id_consents": {
        "bodyRequired": False,
        "bodyRequiredFields": [],
        "clientDefaults": {},
        "contentType": None,
        "credentials": {"password": "query", "username": "query"},
        "hasBody": False,
        "method": "GET",
        "operationId": "get_v2_iys_campaigns_id_consents",
        "parameters": [
            {"location": "path", "publicName": "id", "required": True, "wireName": "id"},
            {"location": "query", "publicName": "offset", "required": False, "wireName": "offset"},
            {"location": "query", "publicName": "limit", "required": False, "wireName": "limit"},
        ],
        "path": "/v2/iys/campaigns/{id}/consents",
        "responseKind": "json",
    },
    "get_v2_iys_campaigns": {
        "bodyRequired": False,
        "bodyRequiredFields": [],
        "clientDefaults": {},
        "contentType": None,
        "credentials": {"password": "query", "username": "query"},
        "hasBody": False,
        "method": "GET",
        "operationId": "get_v2_iys_campaigns",
        "parameters": [
            {"location": "query", "publicName": "offset", "required": False, "wireName": "offset"},
            {"location": "query", "publicName": "limit", "required": False, "wireName": "limit"},
            {"location": "query", "publicName": "source", "required": False, "wireName": "source"},
        ],
        "path": "/v2/iys/campaigns",
        "responseKind": "json",
    },
    "get_v2_headers": {
        "bodyRequired": False,
        "bodyRequiredFields": [],
        "clientDefaults": {},
        "contentType": None,
        "credentials": {"password": "query", "username": "query"},
        "hasBody": False,
        "method": "GET",
        "operationId": "get_v2_headers",
        "parameters": [],
        "path": "/v2/headers",
        "responseKind": "json",
    },
    "sendSmsJson": {
        "bodyRequired": False,
        "bodyRequiredFields": ["username", "password", "messages"],
        "clientDefaults": {"source_addr": "sourceAddr"},
        "contentType": "application/json",
        "credentials": {"password": "body", "username": "body"},
        "hasBody": True,
        "method": "POST",
        "operationId": "sendSmsJson",
        "parameters": [],
        "path": "/v2/send.json",
        "responseKind": "text",
    },
    "get_v2_send": {
        "bodyRequired": False,
        "bodyRequiredFields": [],
        "clientDefaults": {"source_addr": "sourceAddr"},
        "contentType": None,
        "credentials": {"password": "query", "username": "query"},
        "hasBody": False,
        "method": "GET",
        "operationId": "get_v2_send",
        "parameters": [
            {"location": "query", "publicName": "dest", "required": True, "wireName": "dest"},
            {"location": "query", "publicName": "msg", "required": True, "wireName": "msg"},
            {
                "location": "query",
                "publicName": "sourceAddr",
                "required": False,
                "wireName": "source_addr",
            },
            {
                "location": "query",
                "publicName": "validFor",
                "required": False,
                "wireName": "valid_for",
            },
            {
                "location": "query",
                "publicName": "datacoding",
                "required": False,
                "wireName": "datacoding",
            },
            {
                "location": "query",
                "publicName": "isCommercial",
                "required": False,
                "wireName": "is_commercial",
            },
            {
                "location": "query",
                "publicName": "iysRecipientType",
                "required": False,
                "wireName": "iys_recipient_type",
            },
            {"location": "query", "publicName": "sendAt", "required": False, "wireName": "send_at"},
        ],
        "path": "/v2/send",
        "responseKind": "text",
    },
    "getSmsStatus": {
        "bodyRequired": False,
        "bodyRequiredFields": [],
        "clientDefaults": {},
        "contentType": None,
        "credentials": {"password": "query", "username": "query"},
        "hasBody": False,
        "method": "GET",
        "operationId": "getSmsStatus",
        "parameters": [
            {"location": "query", "publicName": "id", "required": False, "wireName": "id"},
            {"location": "query", "publicName": "dest", "required": False, "wireName": "dest"},
            {
                "location": "query",
                "publicName": "greaterThan",
                "required": False,
                "wireName": "greater_than",
            },
            {
                "location": "query",
                "publicName": "customId",
                "required": False,
                "wireName": "custom_id",
            },
        ],
        "path": "/v2/status",
        "responseKind": "json",
    },
    "post_v2_iys_consents_json": {
        "bodyRequired": False,
        "bodyRequiredFields": ["username", "password", "source_addr", "consents"],
        "clientDefaults": {"source_addr": "sourceAddr"},
        "contentType": "application/json",
        "credentials": {"password": "body", "username": "body"},
        "hasBody": True,
        "method": "POST",
        "operationId": "post_v2_iys_consents_json",
        "parameters": [],
        "path": "/v2/iys_consents.json",
        "responseKind": "text",
    },
}


class SmsFacadeMixin(SyncClientBase):
    def add_blacklist_entry(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return self._facade_request(_OPERATIONS["post_v2_blacklists"], input, values)

    def cancel(self, input: Mapping[str, object] | None = None, **values: object) -> object:
        return self._facade_request(_OPERATIONS["post_v2_cancel_id"], input, values)

    def delete_blacklist_entry(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return self._facade_request(_OPERATIONS["delete_v2_blacklists_id"], input, values)

    def list_blacklist_entries(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return self._facade_request(_OPERATIONS["get_v2_blacklists"], input, values)

    def list_inbound_messages(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return self._facade_request(_OPERATIONS["get_v2_inbound_messages"], input, values)

    def list_iys_campaign_consents(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return self._facade_request(_OPERATIONS["get_v2_iys_campaigns_id_consents"], input, values)

    def list_iys_campaigns(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return self._facade_request(_OPERATIONS["get_v2_iys_campaigns"], input, values)

    def list_sender_ids(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return self._facade_request(_OPERATIONS["get_v2_headers"], input, values)

    def send_legacy(self, input: Mapping[str, object] | None = None, **values: object) -> object:
        return self._facade_request(_OPERATIONS["get_v2_send"], input, values)

    def submit_iys_consents(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return self._facade_request(_OPERATIONS["post_v2_iys_consents_json"], input, values)


class AsyncSmsFacadeMixin(AsyncClientBase):
    async def add_blacklist_entry(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return await self._facade_request_async(_OPERATIONS["post_v2_blacklists"], input, values)

    async def cancel(self, input: Mapping[str, object] | None = None, **values: object) -> object:
        return await self._facade_request_async(_OPERATIONS["post_v2_cancel_id"], input, values)

    async def delete_blacklist_entry(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return await self._facade_request_async(
            _OPERATIONS["delete_v2_blacklists_id"], input, values
        )

    async def list_blacklist_entries(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return await self._facade_request_async(_OPERATIONS["get_v2_blacklists"], input, values)

    async def list_inbound_messages(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return await self._facade_request_async(
            _OPERATIONS["get_v2_inbound_messages"], input, values
        )

    async def list_iys_campaign_consents(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return await self._facade_request_async(
            _OPERATIONS["get_v2_iys_campaigns_id_consents"], input, values
        )

    async def list_iys_campaigns(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return await self._facade_request_async(_OPERATIONS["get_v2_iys_campaigns"], input, values)

    async def list_sender_ids(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return await self._facade_request_async(_OPERATIONS["get_v2_headers"], input, values)

    async def send_legacy(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return await self._facade_request_async(_OPERATIONS["get_v2_send"], input, values)

    async def submit_iys_consents(
        self, input: Mapping[str, object] | None = None, **values: object
    ) -> object:
        return await self._facade_request_async(
            _OPERATIONS["post_v2_iys_consents_json"], input, values
        )
