# Code generated by scripts/facades.py. DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping

from verimor._core import AsyncClientBase, SyncClientBase

_OPERATIONS: dict[str, dict[str, object]] = {
    "health_health_get": {
        "bodyRequiredFields": [],
        "clientDefaults": {},
        "contentType": None,
        "credentials": {},
        "hasBody": False,
        "method": "GET",
        "operationId": "health_health_get",
        "parameters": [],
        "path": "/health",
        "responseKind": "json",
    },
    "send_otp_v1_messages_otp_post": {
        "bodyRequiredFields": ["to", "template_name"],
        "clientDefaults": {},
        "contentType": "application/json",
        "credentials": {"x-api-key": "header"},
        "hasBody": True,
        "method": "POST",
        "operationId": "send_otp_v1_messages_otp_post",
        "parameters": [],
        "path": "/v1/messages/otp",
        "responseKind": "json",
    },
    "send_utility_v1_messages_utility_post": {
        "bodyRequiredFields": ["to", "template_name"],
        "clientDefaults": {},
        "contentType": "application/json",
        "credentials": {"x-api-key": "header"},
        "hasBody": True,
        "method": "POST",
        "operationId": "send_utility_v1_messages_utility_post",
        "parameters": [],
        "path": "/v1/messages/utility",
        "responseKind": "json",
    },
}


class WhatsAppFacadeMixin(SyncClientBase):
    def health(self, input: Mapping[str, object] | None = None, **values: object) -> object:
        return self._facade_request(_OPERATIONS["health_health_get"], input, values)


class AsyncWhatsAppFacadeMixin(AsyncClientBase):
    async def health(self, input: Mapping[str, object] | None = None, **values: object) -> object:
        return await self._facade_request_async(_OPERATIONS["health_health_get"], input, values)
