// Package verimorsms provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorsms

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/oapi-codegen/runtime"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

func (c *Client) GetV2Blacklists(ctx context.Context, params *GetV2BlacklistsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2BlacklistsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV2Blacklists(ctx context.Context, params *PostV2BlacklistsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV2BlacklistsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteV2BlacklistsId(ctx context.Context, id string, params *DeleteV2BlacklistsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteV2BlacklistsIdRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func NewGetV2BlacklistsRequest(server string, params *GetV2BlacklistsParams) (*http.Request, error) {
	var err error
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/v2/blacklists")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	if params != nil {
		queryValues := queryURL.Query()
		var rawQueryFragments []string// GetV2Blacklists Kara Liste Görüntüleme
		//
		// <p>Kara listedeki numaraları listelemek için kullanılır.</p><p>Bu endpoint, kullanıcı adı ve şifre ile kimlik doğrulaması gerektirir.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
		//
		// Corresponds with GET /v2/blacklists (the `GetV2Blacklists` operationId).
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "username", params.Username, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "password", params.Password, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if params.Offset != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Limit != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}
	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func NewPostV2BlacklistsRequest(server string, params *PostV2BlacklistsParams) (*http.Request, error) {
	var err error
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/v2/blacklists")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	if params != nil {
		queryValues := queryURL.Query()
		var rawQueryFragments []string// NewPostV2BlacklistsRequest constructs an http.Request for the PostV2Blacklists method
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "username", params.Username, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "password", params.Password, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "phones", params.Phones, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}
	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func NewDeleteV2BlacklistsIdRequest(server string, id string, params *DeleteV2BlacklistsIdParams) (*http.Request, error) {
	var err error
	var pathParam0 string
	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/v2/blacklists/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	if params != nil {
		queryValues := queryURL.Query()
		var rawQueryFragments []string// NewDeleteV2BlacklistsIdRequest constructs an http.Request for the DeleteV2BlacklistsId method
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "username", params.Username, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "password", params.Password, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}
	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func (r GetV2BlacklistsResponse) GetJSON200() *struct {
	Records *[]struct// GetJSON200 returns the response for an HTTP 200 `application/json` response
	{
		CreatedAt *time.Time `json:"created_at,omitempty"`
		Phone     *string    `json:"phone,omitempty"`
		Source    *string    `json:"source,omitempty"`
	} `json:"records,omitempty"`
	Total *int `json:"total,omitempty"`
} {
	return r.JSON200
}

func (r GetV2BlacklistsResponse) GetBody() []byte {// CreatedAt Kara listeye eklenme tarih saati
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r GetV2BlacklistsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r GetV2BlacklistsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r GetV2BlacklistsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r PostV2BlacklistsResponse) GetBody() []byte {// Status returns HTTPResponse.Status
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r PostV2BlacklistsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r PostV2BlacklistsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r PostV2BlacklistsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r DeleteV2BlacklistsIdResponse) GetBody() []byte {// Status returns HTTPResponse.Status
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r DeleteV2BlacklistsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r DeleteV2BlacklistsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r DeleteV2BlacklistsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (c *ClientWithResponses) GetV2BlacklistsWithResponse(ctx context.Context, params *GetV2BlacklistsParams, reqEditors ...RequestEditorFn) (*GetV2BlacklistsResponse, error) {
	rsp, err := c.GetV2Blacklists(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2BlacklistsResponse(rsp)
}

func (c *ClientWithResponses) PostV2BlacklistsWithResponse(ctx context.Context, params *PostV2BlacklistsParams, reqEditors ...RequestEditorFn) (*PostV2BlacklistsResponse, error) {
	rsp, err := c.PostV2Blacklists(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV2BlacklistsResponse(rsp)
}

func (c *ClientWithResponses) DeleteV2BlacklistsIdWithResponse(ctx context.Context, id string, params *DeleteV2BlacklistsIdParams, reqEditors ...RequestEditorFn) (*DeleteV2BlacklistsIdResponse, error) {
	rsp, err := c.DeleteV2BlacklistsId(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteV2BlacklistsIdResponse(rsp)
}

func ParseGetV2BlacklistsResponse(rsp *http.Response) (*GetV2BlacklistsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &GetV2BlacklistsResponse{Body: bodyBytes, HTTPResponse: rsp}
	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Records *[]struct// Status returns HTTPResponse.Status
			// ParseGetV2BlacklistsResponse parses an HTTP response from a GetV2BlacklistsWithResponse call
			{
				CreatedAt *time.Time `json:"created_at,omitempty"`
				Phone     *string    `json:"phone,omitempty"`
				Source    *string    `json:"source,omitempty"`
			} `json:"records,omitempty"`
			Total *int `json:"total,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}
	return response, nil
}

func ParsePostV2BlacklistsResponse(rsp *http.Response) (*PostV2BlacklistsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &PostV2BlacklistsResponse{Body: bodyBytes, HTTPResponse: rsp}
	return response, nil
}

func ParseDeleteV2BlacklistsIdResponse(rsp *http.Response) (*DeleteV2BlacklistsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &DeleteV2BlacklistsIdResponse{Body: bodyBytes, HTTPResponse: rsp}
	return response, nil
}

// CreatedAt Kara listeye eklenme tarih saati
// ParseDeleteV2BlacklistsIdResponse parses an HTTP response from a DeleteV2BlacklistsIdWithResponse call
