// Package verimorsms provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorsms

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/oapi-codegen/runtime"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

func (c *Client) GetV2InboundMessages(ctx context.Context, params *GetV2InboundMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2InboundMessagesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSmsStatus(ctx context.Context, params *GetSmsStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSmsStatusRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func NewGetV2InboundMessagesRequest(server string, params *GetV2InboundMessagesParams) (*http.Request, error) {
	var err error
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/v2/inbound_messages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	if params != nil {
		queryValues := queryURL.Query()
		var rawQueryFragments []string// GetV2InboundMessages Gelen SMS Sorgulama
		//
		// <p>Bu API, gelen SMS'lerinizi sorgulamak için kullanılır.</p><p>API, hesabınıza gelen SMS'leri iki farklı yöntemle teslim edebilir. Bunlar PUSH ve GET yöntemleridir.</p><p>Bu servis&nbsp;<strong>HTTP GET ile Gelen SMS Alımı</strong>&nbsp;hizmetini sağlar. PUSH ile Gelen SMS Alımı konusu için Inbound Bölümü altındaki ilgili başlığa bakabilirsiniz.<br></p><p>Sorgulama, belirli bir zaman aralığında veya belirli bir message_id'den büyük mesajları almak için yapılabilir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
		//
		// Corresponds with GET /v2/inbound_messages (the `GetV2InboundMessages` operationId).
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "username", params.Username, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "password", params.Password, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if params.FromTime != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "from_time", *params.FromTime, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.ToTime != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "to_time", *params.ToTime, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.GreaterThan != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "greater_than", *params.GreaterThan, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}
	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func NewGetSmsStatusRequest(server string, params *GetSmsStatusParams) (*http.Request, error) {
	var err error
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/v2/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	if params != nil {
		queryValues := queryURL.Query()
		var rawQueryFragments []string// NewGetSmsStatusRequest constructs an http.Request for the GetSmsStatus method
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "username", params.Username, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "password", params.Password, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}
		if params.Id != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", *params.Id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.Dest != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dest", *params.Dest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.GreaterThan != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "greater_than", *params.GreaterThan, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if params.CustomId != nil {
			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "custom_id", *params.CustomId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}
		}
		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}
	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func (r GetV2InboundMessagesResponse) GetJSON200() *[]struct// GetJSON200 returns the response for an HTTP 200 `application/json` response
{
	Content         *string    `json:"content,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	DestinationAddr *string    `json:"destination_addr,omitempty"`
	Keyword         *string    `json:"keyword,omitempty"`
	MessageId       *int       `json:"message_id,omitempty"`
	Network         *string    `json:"network,omitempty"`
	ReceivedAt      *time.Time `json:"received_at,omitempty"`
	SourceAddr      *string    `json:"source_addr,omitempty"`
} {
	return r.JSON200
}

func (r GetV2InboundMessagesResponse) GetBody() []byte {// GetBody returns the raw response body bytes

	return r.Body
}

func (r GetV2InboundMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r GetV2InboundMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r GetV2InboundMessagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r GetSmsStatusResponse) GetJSON200() *[]struct// Status returns HTTPResponse.Status
// GetJSON200 returns the response for an HTTP 200 `application/json` response
{
	CampaignCustomId        *string    `json:"campaign_custom_id,omitempty"`
	CampaignId              *int       `json:"campaign_id,omitempty"`
	Credits                 *int       `json:"credits,omitempty"`
	Dest                    *string    `json:"dest,omitempty"`
	DoneAt                  *time.Time `json:"done_at,omitempty"`
	GsmError                *string    `json:"gsm_error,omitempty"`
	InternationalMultiplier *int       `json:"international_multiplier,omitempty"`
	MessageCustomId         *string    `json:"message_custom_id,omitempty"`
	MessageId               *int       `json:"message_id,omitempty"`
	SentAt                  *time.Time `json:"sent_at,omitempty"`
	Size                    *int       `json:"size,omitempty"`
	Status                  *string    `json:"status,omitempty"`
} {
	return r.JSON200
}

func (r GetSmsStatusResponse) GetBody() []byte {// GetBody returns the raw response body bytes

	return r.Body
}

func (r GetSmsStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r GetSmsStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r GetSmsStatusResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (c *ClientWithResponses) GetV2InboundMessagesWithResponse(ctx context.Context, params *GetV2InboundMessagesParams, reqEditors ...RequestEditorFn) (*GetV2InboundMessagesResponse, error) {
	rsp, err := c.GetV2InboundMessages(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2InboundMessagesResponse(rsp)
}

func (c *ClientWithResponses) GetSmsStatusWithResponse(ctx context.Context, params *GetSmsStatusParams, reqEditors ...RequestEditorFn) (*GetSmsStatusResponse, error) {
	rsp, err := c.GetSmsStatus(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSmsStatusResponse(rsp)
}

func ParseGetV2InboundMessagesResponse(rsp *http.Response) (*GetV2InboundMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &GetV2InboundMessagesResponse{Body: bodyBytes, HTTPResponse: rsp}
	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct// Status returns HTTPResponse.Status
		// ParseGetV2InboundMessagesResponse parses an HTTP response from a GetV2InboundMessagesWithResponse call
		{
			Content         *string    `json:"content,omitempty"`
			CreatedAt       *time.Time `json:"created_at,omitempty"`
			DestinationAddr *string    `json:"destination_addr,omitempty"`
			Keyword         *string    `json:"keyword,omitempty"`
			MessageId       *int       `json:"message_id,omitempty"`
			Network         *string    `json:"network,omitempty"`
			ReceivedAt      *time.Time `json:"received_at,omitempty"`
			SourceAddr      *string    `json:"source_addr,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}
	return response, nil
}

func ParseGetSmsStatusResponse(rsp *http.Response) (*GetSmsStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &GetSmsStatusResponse{Body: bodyBytes, HTTPResponse: rsp}
	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct// ParseGetSmsStatusResponse parses an HTTP response from a GetSmsStatusWithResponse call
		{
			CampaignCustomId        *string    `json:"campaign_custom_id,omitempty"`
			CampaignId              *int       `json:"campaign_id,omitempty"`
			Credits                 *int       `json:"credits,omitempty"`
			Dest                    *string    `json:"dest,omitempty"`
			DoneAt                  *time.Time `json:"done_at,omitempty"`
			GsmError                *string    `json:"gsm_error,omitempty"`
			InternationalMultiplier *int       `json:"international_multiplier,omitempty"`
			MessageCustomId         *string    `json:"message_custom_id,omitempty"`
			MessageId               *int       `json:"message_id,omitempty"`
			SentAt                  *time.Time `json:"sent_at,omitempty"`
			Size                    *int       `json:"size,omitempty"`
			Status                  *string    `json:"status,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}
	return response, nil
}
