// Package verimorsms provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorsms

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/oapi-codegen/runtime"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// GetV2IysCampaigns İYS Kampanyaları Listeleme
//
// <p>Gönderilen İYS izinleri ve İYS günlük vatandaş izin değişiklikleri için kampanyalar oluşturulur. Bu kampanyalar bu servisi kullanarak görülebilir.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpointlerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
//
// Corresponds with GET /v2/iys/campaigns (the `GetV2IysCampaigns` operationId).
func (c *Client) GetV2IysCampaigns(ctx context.Context, params *GetV2IysCampaignsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2IysCampaignsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetV2IysCampaignsIdConsents İYS İzinleri Sorgulama
//
// <p>Gönderilen İYS izinleri ve İYS günlük vatandaş izin değişikliklerini kampanya idsi ile sorgulayabilirsiniz.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpointlerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
//
// Corresponds with GET /v2/iys/campaigns/{id}/consents (the `GetV2IysCampaignsIdConsents` operationId).
func (c *Client) GetV2IysCampaignsIdConsents(ctx context.Context, id int, params *GetV2IysCampaignsIdConsentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2IysCampaignsIdConsentsRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostV2IysConsentsJsonWithBody İzin Yönetimi
//
// <p>Ticari ileti göndermek için markalarınızı İYSye (İleti Yönetim Sistemi) kaydettirmiş olmalı ve&nbsp;<a href="https://oim.verimor.com.tr/headers" rel="nofollow">OİM Başlık Yönetiminden</a>&nbsp;ilgili başlığa İYS kodlarını girmiş olmanız gerekir. Bu işlemleri yaptıktan sonra müşterilerinizden aldığınız izinleri bu yöntemle İYSye bildirebilirsiniz.</p><p>Aşağıdaki örnekte olduğu gibi bir JSON string POST edilir.</p><p>Daha sonra istenirse, "İYS İZİNLERİ RAPORU" başlığı altındaki dökümandan faydalanılarak, gönderilen izinlerin durumları alınabilir.</p><p>Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).</p>
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v2/iys_consents.json (the `PostV2IysConsentsJson` operationId).
func (c *Client) PostV2IysConsentsJsonWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV2IysConsentsJsonRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostV2IysConsentsJson İzin Yönetimi
//
// <p>Ticari ileti göndermek için markalarınızı İYSye (İleti Yönetim Sistemi) kaydettirmiş olmalı ve&nbsp;<a href="https://oim.verimor.com.tr/headers" rel="nofollow">OİM Başlık Yönetiminden</a>&nbsp;ilgili başlığa İYS kodlarını girmiş olmanız gerekir. Bu işlemleri yaptıktan sonra müşterilerinizden aldığınız izinleri bu yöntemle İYSye bildirebilirsiniz.</p><p>Aşağıdaki örnekte olduğu gibi bir JSON string POST edilir.</p><p>Daha sonra istenirse, "İYS İZİNLERİ RAPORU" başlığı altındaki dökümandan faydalanılarak, gönderilen izinlerin durumları alınabilir.</p><p>Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).</p>
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v2/iys_consents.json (the `PostV2IysConsentsJson` operationId).
func (c *Client) PostV2IysConsentsJson(ctx context.Context, body PostV2IysConsentsJsonJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV2IysConsentsJsonRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV2IysCampaignsRequest constructs an http.Request for the GetV2IysCampaigns method
func NewGetV2IysCampaignsRequest(server string, params *GetV2IysCampaignsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/iys/campaigns")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "username", params.Username, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "password", params.Password, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Source != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "source", *params.Source, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV2IysCampaignsIdConsentsRequest constructs an http.Request for the GetV2IysCampaignsIdConsents method
func NewGetV2IysCampaignsIdConsentsRequest(server string, id int, params *GetV2IysCampaignsIdConsentsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/iys/campaigns/%s/consents", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "username", params.Username, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "password", params.Password, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV2IysConsentsJsonRequest calls the generic PostV2IysConsentsJson builder with application/json body
func NewPostV2IysConsentsJsonRequest(server string, body PostV2IysConsentsJsonJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV2IysConsentsJsonRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV2IysConsentsJsonRequestWithBody constructs an http.Request for the PostV2IysConsentsJson method, with any body, and a specified content type
func NewPostV2IysConsentsJsonRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/iys_consents.json")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetV2IysCampaignsResponse) GetJSON200() *struct {
	Records []struct {
		CreatedAt    *time.Time `json:"created_at,omitempty"`
		HeaderName   *string    `json:"header_name,omitempty"`
		Id           *int       `json:"id,omitempty"`
		IysBrandCode *int       `json:"iys_brand_code,omitempty"`
		IysCode      *int       `json:"iys_code,omitempty"`
		Source       *string    `json:"source,omitempty"`
	} `json:"records"`
	Total int `json:"total"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetV2IysCampaignsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetV2IysCampaignsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV2IysCampaignsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetV2IysCampaignsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetV2IysCampaignsIdConsentsResponse) GetJSON200() *struct {
	Records []struct {
		ConsentDate   *time.Time `json:"consent_date,omitempty"`
		Recipient     *string    `json:"recipient,omitempty"`
		RecipientType *string    `json:"recipient_type,omitempty"`
		RequestError  *string    `json:"request_error,omitempty"`
		RequestStatus *string    `json:"request_status,omitempty"`
		Source        *string    `json:"source,omitempty"`
		Status        *string    `json:"status,omitempty"`
		Type          *string    `json:"type,omitempty"`
	} `json:"records"`
	SourceAddr string `json:"source_addr"`
	Status     string `json:"status"`
	Total      int    `json:"total"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetV2IysCampaignsIdConsentsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetV2IysCampaignsIdConsentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV2IysCampaignsIdConsentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetV2IysCampaignsIdConsentsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBody returns the raw response body bytes
func (r PostV2IysConsentsJsonResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostV2IysConsentsJsonResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV2IysConsentsJsonResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostV2IysConsentsJsonResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetV2IysCampaignsWithResponse İYS Kampanyaları Listeleme
//
// <p>Gönderilen İYS izinleri ve İYS günlük vatandaş izin değişiklikleri için kampanyalar oluşturulur. Bu kampanyalar bu servisi kullanarak görülebilir.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpointlerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v2/iys/campaigns (the `GetV2IysCampaigns` operationId).
func (c *ClientWithResponses) GetV2IysCampaignsWithResponse(ctx context.Context, params *GetV2IysCampaignsParams, reqEditors ...RequestEditorFn) (*GetV2IysCampaignsResponse, error) {
	rsp, err := c.GetV2IysCampaigns(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2IysCampaignsResponse(rsp)
}

// GetV2IysCampaignsIdConsentsWithResponse İYS İzinleri Sorgulama
//
// <p>Gönderilen İYS izinleri ve İYS günlük vatandaş izin değişikliklerini kampanya idsi ile sorgulayabilirsiniz.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpointlerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v2/iys/campaigns/{id}/consents (the `GetV2IysCampaignsIdConsents` operationId).
func (c *ClientWithResponses) GetV2IysCampaignsIdConsentsWithResponse(ctx context.Context, id int, params *GetV2IysCampaignsIdConsentsParams, reqEditors ...RequestEditorFn) (*GetV2IysCampaignsIdConsentsResponse, error) {
	rsp, err := c.GetV2IysCampaignsIdConsents(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2IysCampaignsIdConsentsResponse(rsp)
}

// PostV2IysConsentsJsonWithBodyWithResponse İzin Yönetimi
//
// <p>Ticari ileti göndermek için markalarınızı İYSye (İleti Yönetim Sistemi) kaydettirmiş olmalı ve&nbsp;<a href="https://oim.verimor.com.tr/headers" rel="nofollow">OİM Başlık Yönetiminden</a>&nbsp;ilgili başlığa İYS kodlarını girmiş olmanız gerekir. Bu işlemleri yaptıktan sonra müşterilerinizden aldığınız izinleri bu yöntemle İYSye bildirebilirsiniz.</p><p>Aşağıdaki örnekte olduğu gibi bir JSON string POST edilir.</p><p>Daha sonra istenirse, "İYS İZİNLERİ RAPORU" başlığı altındaki dökümandan faydalanılarak, gönderilen izinlerin durumları alınabilir.</p><p>Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).</p>
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v2/iys_consents.json (the `PostV2IysConsentsJson` operationId).
func (c *ClientWithResponses) PostV2IysConsentsJsonWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV2IysConsentsJsonResponse, error) {
	rsp, err := c.PostV2IysConsentsJsonWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV2IysConsentsJsonResponse(rsp)
}

// PostV2IysConsentsJsonWithResponse İzin Yönetimi
//
// <p>Ticari ileti göndermek için markalarınızı İYSye (İleti Yönetim Sistemi) kaydettirmiş olmalı ve&nbsp;<a href="https://oim.verimor.com.tr/headers" rel="nofollow">OİM Başlık Yönetiminden</a>&nbsp;ilgili başlığa İYS kodlarını girmiş olmanız gerekir. Bu işlemleri yaptıktan sonra müşterilerinizden aldığınız izinleri bu yöntemle İYSye bildirebilirsiniz.</p><p>Aşağıdaki örnekte olduğu gibi bir JSON string POST edilir.</p><p>Daha sonra istenirse, "İYS İZİNLERİ RAPORU" başlığı altındaki dökümandan faydalanılarak, gönderilen izinlerin durumları alınabilir.</p><p>Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).</p>
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v2/iys_consents.json (the `PostV2IysConsentsJson` operationId).
func (c *ClientWithResponses) PostV2IysConsentsJsonWithResponse(ctx context.Context, body PostV2IysConsentsJsonJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV2IysConsentsJsonResponse, error) {
	rsp, err := c.PostV2IysConsentsJson(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV2IysConsentsJsonResponse(rsp)
}

// ParseGetV2IysCampaignsResponse parses an HTTP response from a GetV2IysCampaignsWithResponse call
func ParseGetV2IysCampaignsResponse(rsp *http.Response) (*GetV2IysCampaignsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV2IysCampaignsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Records []struct {
				CreatedAt    *time.Time `json:"created_at,omitempty"`
				HeaderName   *string    `json:"header_name,omitempty"`
				Id           *int       `json:"id,omitempty"`
				IysBrandCode *int       `json:"iys_brand_code,omitempty"`
				IysCode      *int       `json:"iys_code,omitempty"`
				Source       *string    `json:"source,omitempty"`
			} `json:"records"`
			Total int `json:"total"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetV2IysCampaignsIdConsentsResponse parses an HTTP response from a GetV2IysCampaignsIdConsentsWithResponse call
func ParseGetV2IysCampaignsIdConsentsResponse(rsp *http.Response) (*GetV2IysCampaignsIdConsentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV2IysCampaignsIdConsentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Records []struct {
				ConsentDate   *time.Time `json:"consent_date,omitempty"`
				Recipient     *string    `json:"recipient,omitempty"`
				RecipientType *string    `json:"recipient_type,omitempty"`
				RequestError  *string    `json:"request_error,omitempty"`
				RequestStatus *string    `json:"request_status,omitempty"`
				Source        *string    `json:"source,omitempty"`
				Status        *string    `json:"status,omitempty"`
				Type          *string    `json:"type,omitempty"`
			} `json:"records"`
			SourceAddr string `json:"source_addr"`
			Status     string `json:"status"`
			Total      int    `json:"total"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostV2IysConsentsJsonResponse parses an HTTP response from a PostV2IysConsentsJsonWithResponse call
func ParsePostV2IysConsentsJsonResponse(rsp *http.Response) (*PostV2IysConsentsJsonResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV2IysConsentsJsonResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
