// Package verimorsms provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorsms

import "net/http"

type GetV2BalanceParams struct {
	Username string `form:"username" json:"username"`
	Password string `form:"password" json:"password"`
}
type GetV2BalanceResponse struct {
	Body []byte// GetV2BalanceParams defines parameters for GetV2Balance.
	// Password Şifre

	HTTPResponse *http.Response
}
