// Package verimorsms provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorsms

import (
	"context"
	"io"
	"net/http"
)

// Defines values for SendSmsJsonJSONBodyDatacoding.
const (
	N0 SendSmsJsonJSONBodyDatacoding = 0
	N1 SendSmsJsonJSONBodyDatacoding = 1
	N2 SendSmsJsonJSONBodyDatacoding = 2
)

// GelenSMSAlimiJSONBody defines parameters for GelenSMSAlimi.
type GelenSMSAlimiJSONBody = []struct {
	// Content Gelen mesajın tam içeriği.
	Content *string `json:"content,omitempty"`

	// CreatedAt Mesajın kayıt edildiği tarih saat. Tarih ve saat aralığına göre API isteklerinde filtre yapılacak alan.
	CreatedAt *string `json:"created_at,omitempty"`

	// DestinationAddr Mesajın gönderildiği numara (Verimor abone numarası veya 4 haneli Verimor ücretsiz kısa numarası).
	DestinationAddr *string `json:"destination_addr,omitempty"`

	// Keyword Ortak kullanımlı kısa numaralardaki ayırt edici anahtar kelime. Kısa numaraya değil doğrudan sizin numaranıza gelen sms'lerde boş olur.
	Keyword *string `json:"keyword,omitempty"`

	// MessageId Mesaja API tarafından verilmiş ID.
	MessageId *int `json:"message_id,omitempty"`

	// Network Mesajı gönderen operatör. TURKCELL, TTMOBIL, VODAFONE değerleri olabilir.
	Network *string `json:"network,omitempty"`

	// ReceivedAt Mesajın alındığı tarih saat.
	ReceivedAt *string `json:"received_at,omitempty"`

	// SourceAddr Mesajı gönderen numara.
	SourceAddr *string `json:"source_addr,omitempty"`

	// Type Mesajın yönüdür. Gelen SMS olduğu için inbound.
	Type *string `json:"type,omitempty"`
}

// GonderimRaporuAlimiJSONBody defines parameters for GonderimRaporuAlimi.
type GonderimRaporuAlimiJSONBody = []struct {
	// CampaignCustomId Mesajın kampanyasına sizin tarafınızdan verilmiş özel ID.
	CampaignCustomId *string `json:"campaign_custom_id,omitempty"`

	// CampaignId Mesajın kampanya ID'si.
	CampaignId *int `json:"campaign_id,omitempty"`

	// Credits Bu mesaj için hesabınızdan kaç kredi düşüldüğü.
	Credits *int `json:"credits,omitempty"`

	// Dest Mesajın gönderildiği telefon numarası. Yurt dışı numaralarının başına 00 eklenmelidir. Örnek: 0049xxxxxxxx.
	Dest *string `json:"dest,omitempty"`

	// DoneAt Mesajın son durumuna ulaştığı tarih (mesaj iletilemediyse de dolu olur).
	DoneAt *string `json:"done_at,omitempty"`

	// GsmError Mesaj iletilemediyse operatörden dönen hata kodu.
	GsmError *string `json:"gsm_error,omitempty"`

	// InternationalMultiplier Mesajın kredi çarpanı (bir boyunun kaç krediye denk geldiği). Uluslararası mesajlarda 1'den büyük olur. Ulusal mesajlarda daima 1 olur.
	InternationalMultiplier *int `json:"international_multiplier,omitempty"`

	// MessageCustomId Mesaja sizin tarafınızdan verilmiş özel ID.
	MessageCustomId *string `json:"message_custom_id,omitempty"`

	// MessageId Mesaja API tarafından verilmiş ID.
	MessageId *string `json:"message_id,omitempty"`

	// SentAt Mesajın iletildiği tarih (mesaj iletilemediyse null olur).
	SentAt *string `json:"sent_at,omitempty"`

	// Size Mesajın boyu.
	Size *int `json:"size,omitempty"`

	// Status Mesajın durumu (olabilecek durumlar ve anlamları için dokümanın sonundaki durum listesine bakınız).
	Status *string `json:"status,omitempty"`

	// Type Mesajın yönüdür. Gönderilen SMS olduğu için outbound.
	Type *string `json:"type,omitempty"`
}

// IYSGunlukVatandasRaporuJSONBody defines parameters for IYSGunlukVatandasRaporu.
type IYSGunlukVatandasRaporuJSONBody struct {
	// IysCampaignId İYS kampanya ID'si.
	IysCampaignId *int `json:"iys_campaign_id,omitempty"`

	// ReportDate Rapor tarihi (YYYY-MM-DD formatında).
	ReportDate *string `json:"report_date,omitempty"`

	// SourceAddr Kampanya başlığı veya kaynak adres.
	SourceAddr *string `json:"source_addr,omitempty"`
}

// GelenSMSAlimiJSONRequestBody defines body for GelenSMSAlimi for application/json ContentType.
type GelenSMSAlimiJSONRequestBody = GelenSMSAlimiJSONBody

// GonderimRaporuAlimiJSONRequestBody defines body for GonderimRaporuAlimi for application/json ContentType.
type GonderimRaporuAlimiJSONRequestBody = GonderimRaporuAlimiJSONBody

// IYSGunlukVatandasRaporuJSONRequestBody defines body for IYSGunlukVatandasRaporu for application/json ContentType.
type IYSGunlukVatandasRaporuJSONRequestBody IYSGunlukVatandasRaporuJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// The interface specification for the client above.
type ClientInterface interface {

	// GetV2Balance Bakiye Sorgulama
	//
	// SMS kalan kredi sorgulama için bu servis kullanılır. İşlem için kullanıcı adı ve şifre gereklidir. Bu endpoint /v2/status, /v2/headers gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).
	//
	// Corresponds with GET /v2/balance (the `GetV2Balance` operationId).
	GetV2Balance(ctx context.Context, params *GetV2BalanceParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2Blacklists Kara Liste Görüntüleme
	//
	// <p>Kara listedeki numaraları listelemek için kullanılır.</p><p>Bu endpoint, kullanıcı adı ve şifre ile kimlik doğrulaması gerektirir.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Corresponds with GET /v2/blacklists (the `GetV2Blacklists` operationId).
	GetV2Blacklists(ctx context.Context, params *GetV2BlacklistsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV2Blacklists Kara Liste Ekleme
	//
	// <p>Kara listeye numara eklemek için kullanılır.</p><p>Bu endpoint, kullanıcı adı ve şifre ile kimlik doğrulaması gerektirir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Corresponds with POST /v2/blacklists (the `PostV2Blacklists` operationId).
	PostV2Blacklists(ctx context.Context, params *PostV2BlacklistsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteV2BlacklistsId Kara Listeden Silme
	//
	// <p>Kara listeden numara(lar)ı silmek için kullanılır.</p><p>Bu endpoint, kullanıcı adı ve şifre ile kimlik doğrulaması gerektirir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Corresponds with DELETE /v2/blacklists/{id} (the `DeleteV2BlacklistsId` operationId).
	DeleteV2BlacklistsId(ctx context.Context, id string, params *DeleteV2BlacklistsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV2CancelIdWithBody Gönderim İptali
	//
	// <p>İleri tarihli mesaj gönderimini iptal etmek için örnekte olduğu gibi bir JSON string POST edilir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v2/cancel/{id} (the `PostV2CancelId` operationId).
	PostV2CancelIdWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV2CancelId Gönderim İptali
	//
	// <p>İleri tarihli mesaj gönderimini iptal etmek için örnekte olduğu gibi bir JSON string POST edilir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v2/cancel/{id} (the `PostV2CancelId` operationId).
	PostV2CancelId(ctx context.Context, id string, body PostV2CancelIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2Headers Başlık Yönetimi
	//
	// Tanımlı SMS Başlıklarını listeler. Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).
	//
	// Corresponds with GET /v2/headers (the `GetV2Headers` operationId).
	GetV2Headers(ctx context.Context, params *GetV2HeadersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2InboundMessages Gelen SMS Sorgulama
	//
	// <p>Bu API, gelen SMS'lerinizi sorgulamak için kullanılır.</p><p>API, hesabınıza gelen SMS'leri iki farklı yöntemle teslim edebilir. Bunlar PUSH ve GET yöntemleridir.</p><p>Bu servis&nbsp;<strong>HTTP GET ile Gelen SMS Alımı</strong>&nbsp;hizmetini sağlar. PUSH ile Gelen SMS Alımı konusu için Inbound Bölümü altındaki ilgili başlığa bakabilirsiniz.<br></p><p>Sorgulama, belirli bir zaman aralığında veya belirli bir message_id'den büyük mesajları almak için yapılabilir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Corresponds with GET /v2/inbound_messages (the `GetV2InboundMessages` operationId).
	GetV2InboundMessages(ctx context.Context, params *GetV2InboundMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2IysCampaigns İYS Kampanyaları Listeleme
	//
	// <p>Gönderilen İYS izinleri ve İYS günlük vatandaş izin değişiklikleri için kampanyalar oluşturulur. Bu kampanyalar bu servisi kullanarak görülebilir.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpointlerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Corresponds with GET /v2/iys/campaigns (the `GetV2IysCampaigns` operationId).
	GetV2IysCampaigns(ctx context.Context, params *GetV2IysCampaignsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2IysCampaignsIdConsents İYS İzinleri Sorgulama
	//
	// <p>Gönderilen İYS izinleri ve İYS günlük vatandaş izin değişikliklerini kampanya idsi ile sorgulayabilirsiniz.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpointlerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Corresponds with GET /v2/iys/campaigns/{id}/consents (the `GetV2IysCampaignsIdConsents` operationId).
	GetV2IysCampaignsIdConsents(ctx context.Context, id int, params *GetV2IysCampaignsIdConsentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV2IysConsentsJsonWithBody İzin Yönetimi
	//
	// <p>Ticari ileti göndermek için markalarınızı İYSye (İleti Yönetim Sistemi) kaydettirmiş olmalı ve&nbsp;<a href="https://oim.verimor.com.tr/headers" rel="nofollow">OİM Başlık Yönetiminden</a>&nbsp;ilgili başlığa İYS kodlarını girmiş olmanız gerekir. Bu işlemleri yaptıktan sonra müşterilerinizden aldığınız izinleri bu yöntemle İYSye bildirebilirsiniz.</p><p>Aşağıdaki örnekte olduğu gibi bir JSON string POST edilir.</p><p>Daha sonra istenirse, "İYS İZİNLERİ RAPORU" başlığı altındaki dökümandan faydalanılarak, gönderilen izinlerin durumları alınabilir.</p><p>Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).</p>
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v2/iys_consents.json (the `PostV2IysConsentsJson` operationId).
	PostV2IysConsentsJsonWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV2IysConsentsJson İzin Yönetimi
	//
	// <p>Ticari ileti göndermek için markalarınızı İYSye (İleti Yönetim Sistemi) kaydettirmiş olmalı ve&nbsp;<a href="https://oim.verimor.com.tr/headers" rel="nofollow">OİM Başlık Yönetiminden</a>&nbsp;ilgili başlığa İYS kodlarını girmiş olmanız gerekir. Bu işlemleri yaptıktan sonra müşterilerinizden aldığınız izinleri bu yöntemle İYSye bildirebilirsiniz.</p><p>Aşağıdaki örnekte olduğu gibi bir JSON string POST edilir.</p><p>Daha sonra istenirse, "İYS İZİNLERİ RAPORU" başlığı altındaki dökümandan faydalanılarak, gönderilen izinlerin durumları alınabilir.</p><p>Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).</p>
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v2/iys_consents.json (the `PostV2IysConsentsJson` operationId).
	PostV2IysConsentsJson(ctx context.Context, body PostV2IysConsentsJsonJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2Send SMS Gönderme (GET)
	//
	// Aynı mesajı birden çok numaraya HTTP(S) GET (Plain de denir) ile gönderir; yanıtı düz metin olarak döner. Farklı numaralara farklı mesaj göndermek için /v2/send.json (POST JSON) kullanın. Bu endpoint /v2/iys_consents.json ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).
	//
	// Corresponds with GET /v2/send (the `GetV2Send` operationId).
	GetV2Send(ctx context.Context, params *GetV2SendParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendSmsJsonWithBody SMS Gönderme (JSON)
	//
	// JSON formatında toplu SMS gönderimi için kullanılır. Birden fazla farklı mesajı farklı numaralara gönderebilirsiniz. Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v2/send.json (the `SendSmsJson` operationId).
	SendSmsJsonWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendSmsJson SMS Gönderme (JSON)
	//
	// JSON formatında toplu SMS gönderimi için kullanılır. Birden fazla farklı mesajı farklı numaralara gönderebilirsiniz. Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v2/send.json (the `SendSmsJson` operationId).
	SendSmsJson(ctx context.Context, body SendSmsJsonJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSmsStatus Rapor Sorgulama (API ID)
	//
	// <p>Gönderim Raporu almak için kullanılır.</p><ul dir="auto"><li>id: Kampanya'ya API tarafından verilen ID'dir. id veya custom_id zorunludur.</li><li>custom_id: Kampanya'ya sizin tarafından verilen ID'dir. id veya custom_id zorunludur.</li><li>dest: Zorunlu değil. Kampanya'da belirli telefon numaralarına gönderilmiş mesajları sorgular.</li><li>greater_than: Verilen message_id'den büyük mesajları sorgular. Bu parametre, içinde çok mesaj olan kampanyaların sorgulanması için zorunludur. Bu sorgu 100 mesaj döndürür, mesajların devamını almak için sonuçtaki son mesaj id'sini vererek ikinci bir sorgu yapmalısınız.</li></ul><p>Bu endpoint /v2/balance, /v2/headers gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Corresponds with GET /v2/status (the `GetSmsStatus` operationId).
	GetSmsStatus(ctx context.Context, params *GetSmsStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetV2BalanceWithResponse Bakiye Sorgulama
	//
	// SMS kalan kredi sorgulama için bu servis kullanılır. İşlem için kullanıcı adı ve şifre gereklidir. Bu endpoint /v2/status, /v2/headers gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v2/balance (the `GetV2Balance` operationId).
	GetV2BalanceWithResponse(ctx context.Context, params *GetV2BalanceParams, reqEditors ...RequestEditorFn) (*GetV2BalanceResponse, error)

	// GetV2BlacklistsWithResponse Kara Liste Görüntüleme
	//
	// <p>Kara listedeki numaraları listelemek için kullanılır.</p><p>Bu endpoint, kullanıcı adı ve şifre ile kimlik doğrulaması gerektirir.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v2/blacklists (the `GetV2Blacklists` operationId).
	GetV2BlacklistsWithResponse(ctx context.Context, params *GetV2BlacklistsParams, reqEditors ...RequestEditorFn) (*GetV2BlacklistsResponse, error)

	// PostV2BlacklistsWithResponse Kara Liste Ekleme
	//
	// <p>Kara listeye numara eklemek için kullanılır.</p><p>Bu endpoint, kullanıcı adı ve şifre ile kimlik doğrulaması gerektirir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v2/blacklists (the `PostV2Blacklists` operationId).
	PostV2BlacklistsWithResponse(ctx context.Context, params *PostV2BlacklistsParams, reqEditors ...RequestEditorFn) (*PostV2BlacklistsResponse, error)

	// DeleteV2BlacklistsIdWithResponse Kara Listeden Silme
	//
	// <p>Kara listeden numara(lar)ı silmek için kullanılır.</p><p>Bu endpoint, kullanıcı adı ve şifre ile kimlik doğrulaması gerektirir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /v2/blacklists/{id} (the `DeleteV2BlacklistsId` operationId).
	DeleteV2BlacklistsIdWithResponse(ctx context.Context, id string, params *DeleteV2BlacklistsIdParams, reqEditors ...RequestEditorFn) (*DeleteV2BlacklistsIdResponse, error)

	// PostV2CancelIdWithBodyWithResponse Gönderim İptali
	//
	// <p>İleri tarihli mesaj gönderimini iptal etmek için örnekte olduğu gibi bir JSON string POST edilir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v2/cancel/{id} (the `PostV2CancelId` operationId).
	PostV2CancelIdWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV2CancelIdResponse, error)

	// PostV2CancelIdWithResponse Gönderim İptali
	//
	// <p>İleri tarihli mesaj gönderimini iptal etmek için örnekte olduğu gibi bir JSON string POST edilir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v2/cancel/{id} (the `PostV2CancelId` operationId).
	PostV2CancelIdWithResponse(ctx context.Context, id string, body PostV2CancelIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV2CancelIdResponse, error)

	// GetV2HeadersWithResponse Başlık Yönetimi
	//
	// Tanımlı SMS Başlıklarını listeler. Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v2/headers (the `GetV2Headers` operationId).
	GetV2HeadersWithResponse(ctx context.Context, params *GetV2HeadersParams, reqEditors ...RequestEditorFn) (*GetV2HeadersResponse, error)

	// GetV2InboundMessagesWithResponse Gelen SMS Sorgulama
	//
	// <p>Bu API, gelen SMS'lerinizi sorgulamak için kullanılır.</p><p>API, hesabınıza gelen SMS'leri iki farklı yöntemle teslim edebilir. Bunlar PUSH ve GET yöntemleridir.</p><p>Bu servis&nbsp;<strong>HTTP GET ile Gelen SMS Alımı</strong>&nbsp;hizmetini sağlar. PUSH ile Gelen SMS Alımı konusu için Inbound Bölümü altındaki ilgili başlığa bakabilirsiniz.<br></p><p>Sorgulama, belirli bir zaman aralığında veya belirli bir message_id'den büyük mesajları almak için yapılabilir.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v2/inbound_messages (the `GetV2InboundMessages` operationId).
	GetV2InboundMessagesWithResponse(ctx context.Context, params *GetV2InboundMessagesParams, reqEditors ...RequestEditorFn) (*GetV2InboundMessagesResponse, error)

	// GetV2IysCampaignsWithResponse İYS Kampanyaları Listeleme
	//
	// <p>Gönderilen İYS izinleri ve İYS günlük vatandaş izin değişiklikleri için kampanyalar oluşturulur. Bu kampanyalar bu servisi kullanarak görülebilir.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpointlerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v2/iys/campaigns (the `GetV2IysCampaigns` operationId).
	GetV2IysCampaignsWithResponse(ctx context.Context, params *GetV2IysCampaignsParams, reqEditors ...RequestEditorFn) (*GetV2IysCampaignsResponse, error)

	// GetV2IysCampaignsIdConsentsWithResponse İYS İzinleri Sorgulama
	//
	// <p>Gönderilen İYS izinleri ve İYS günlük vatandaş izin değişikliklerini kampanya idsi ile sorgulayabilirsiniz.</p><p><strong>Total</strong>&nbsp;değeri toplam kayıt sayısını verir, bir sorguda en fazla 100 adet kayıt dönülür. Devamını almak için offset değerini yükseltip tekrar sorgulamalısınız.</p><p>Bu endpoint /v2/status, /v2/balance gibi endpointlerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v2/iys/campaigns/{id}/consents (the `GetV2IysCampaignsIdConsents` operationId).
	GetV2IysCampaignsIdConsentsWithResponse(ctx context.Context, id int, params *GetV2IysCampaignsIdConsentsParams, reqEditors ...RequestEditorFn) (*GetV2IysCampaignsIdConsentsResponse, error)

	// PostV2IysConsentsJsonWithBodyWithResponse İzin Yönetimi
	//
	// <p>Ticari ileti göndermek için markalarınızı İYSye (İleti Yönetim Sistemi) kaydettirmiş olmalı ve&nbsp;<a href="https://oim.verimor.com.tr/headers" rel="nofollow">OİM Başlık Yönetiminden</a>&nbsp;ilgili başlığa İYS kodlarını girmiş olmanız gerekir. Bu işlemleri yaptıktan sonra müşterilerinizden aldığınız izinleri bu yöntemle İYSye bildirebilirsiniz.</p><p>Aşağıdaki örnekte olduğu gibi bir JSON string POST edilir.</p><p>Daha sonra istenirse, "İYS İZİNLERİ RAPORU" başlığı altındaki dökümandan faydalanılarak, gönderilen izinlerin durumları alınabilir.</p><p>Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).</p>
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v2/iys_consents.json (the `PostV2IysConsentsJson` operationId).
	PostV2IysConsentsJsonWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV2IysConsentsJsonResponse, error)

	// PostV2IysConsentsJsonWithResponse İzin Yönetimi
	//
	// <p>Ticari ileti göndermek için markalarınızı İYSye (İleti Yönetim Sistemi) kaydettirmiş olmalı ve&nbsp;<a href="https://oim.verimor.com.tr/headers" rel="nofollow">OİM Başlık Yönetiminden</a>&nbsp;ilgili başlığa İYS kodlarını girmiş olmanız gerekir. Bu işlemleri yaptıktan sonra müşterilerinizden aldığınız izinleri bu yöntemle İYSye bildirebilirsiniz.</p><p>Aşağıdaki örnekte olduğu gibi bir JSON string POST edilir.</p><p>Daha sonra istenirse, "İYS İZİNLERİ RAPORU" başlığı altındaki dökümandan faydalanılarak, gönderilen izinlerin durumları alınabilir.</p><p>Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).</p>
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v2/iys_consents.json (the `PostV2IysConsentsJson` operationId).
	PostV2IysConsentsJsonWithResponse(ctx context.Context, body PostV2IysConsentsJsonJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV2IysConsentsJsonResponse, error)

	// GetV2SendWithResponse SMS Gönderme (GET)
	//
	// Aynı mesajı birden çok numaraya HTTP(S) GET (Plain de denir) ile gönderir; yanıtı düz metin olarak döner. Farklı numaralara farklı mesaj göndermek için /v2/send.json (POST JSON) kullanın. Bu endpoint /v2/iys_consents.json ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v2/send (the `GetV2Send` operationId).
	GetV2SendWithResponse(ctx context.Context, params *GetV2SendParams, reqEditors ...RequestEditorFn) (*GetV2SendResponse, error)

	// SendSmsJsonWithBodyWithResponse SMS Gönderme (JSON)
	//
	// JSON formatında toplu SMS gönderimi için kullanılır. Birden fazla farklı mesajı farklı numaralara gönderebilirsiniz. Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v2/send.json (the `SendSmsJson` operationId).
	SendSmsJsonWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendSmsJsonResponse, error)

	// SendSmsJsonWithResponse SMS Gönderme (JSON)
	//
	// JSON formatında toplu SMS gönderimi için kullanılır. Birden fazla farklı mesajı farklı numaralara gönderebilirsiniz. Bu endpoint /v2/send ile aynı hız sınırı havuzunu paylaşır — dakikada toplam 240 istek gönderebilirsiniz (burst 80).
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v2/send.json (the `SendSmsJson` operationId).
	SendSmsJsonWithResponse(ctx context.Context, body SendSmsJsonJSONRequestBody, reqEditors ...RequestEditorFn) (*SendSmsJsonResponse, error)

	// GetSmsStatusWithResponse Rapor Sorgulama (API ID)
	//
	// <p>Gönderim Raporu almak için kullanılır.</p><ul dir="auto"><li>id: Kampanya'ya API tarafından verilen ID'dir. id veya custom_id zorunludur.</li><li>custom_id: Kampanya'ya sizin tarafından verilen ID'dir. id veya custom_id zorunludur.</li><li>dest: Zorunlu değil. Kampanya'da belirli telefon numaralarına gönderilmiş mesajları sorgular.</li><li>greater_than: Verilen message_id'den büyük mesajları sorgular. Bu parametre, içinde çok mesaj olan kampanyaların sorgulanması için zorunludur. Bu sorgu 100 mesaj döndürür, mesajların devamını almak için sonuçtaki son mesaj id'sini vererek ikinci bir sorgu yapmalısınız.</li></ul><p>Bu endpoint /v2/balance, /v2/headers gibi endpoint'lerle aynı hız sınırı havuzunu paylaşır — dakikada toplam 20 istek gönderebilirsiniz (burst 10).</p>
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v2/status (the `GetSmsStatus` operationId).
	GetSmsStatusWithResponse(ctx context.Context, params *GetSmsStatusParams, reqEditors ...RequestEditorFn) (*GetSmsStatusResponse, error)
}

// WebhookInitiator sends OpenAPI 3.1 webhook requests to target URLs.
// Modeled on the generated Client, but with no stored Server -- the full
// target URL is provided per-call by the caller (typically discovered
// from a subscription registration).
type WebhookInitiator struct {
	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// WebhookInitiatorOption allows setting custom parameters during construction.
type WebhookInitiatorOption func(*WebhookInitiator) error

// WebhookInitiatorInterface is the interface specification for the webhook initiator.
type WebhookInitiatorInterface interface {
	// GelenSMSAlimiWithBody fires the GelenSMSAlimi webhook with any body
	GelenSMSAlimiWithBody(ctx context.Context, targetURL string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GelenSMSAlimi(ctx context.Context, targetURL string, body GelenSMSAlimiJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GonderimRaporuAlimiWithBody fires the GonderimRaporuAlimi webhook with any body
	GonderimRaporuAlimiWithBody(ctx context.Context, targetURL string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GonderimRaporuAlimi(ctx context.Context, targetURL string, body GonderimRaporuAlimiJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// IYSGunlukVatandasRaporuWithBody fires the IYSGunlukVatandasRaporu webhook with any body
	IYSGunlukVatandasRaporuWithBody(ctx context.Context, targetURL string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	IYSGunlukVatandasRaporu(ctx context.Context, targetURL string, body IYSGunlukVatandasRaporuJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}
