// Package verimorsms provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorsms

import "net/http"

// GetV2HeadersParams defines parameters for GetV2Headers.
type GetV2HeadersParams struct {
	// Username Kullanıcı Adı
	Username string `form:"username" json:"username"`

	// Password Şifre
	Password string `form:"password" json:"password"`
}

type GetV2HeadersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]string
}
