// Code generated by scripts/facades.py. DO NOT EDIT.

import type { FacadeTransport } from "../core.js";

export interface SmsFacade {
  addBlacklistEntry(input?: Readonly<Record<string, unknown>>): Promise<string>;
  balance(input?: Readonly<Record<string, unknown>>): Promise<string>;
  cancel(input?: Readonly<Record<string, unknown>>): Promise<string>;
  deleteBlacklistEntry(input?: Readonly<Record<string, unknown>>): Promise<string>;
  listBlacklistEntries(input?: Readonly<Record<string, unknown>>): Promise<unknown>;
  listInboundMessages(input?: Readonly<Record<string, unknown>>): Promise<unknown>;
  listIysCampaignConsents(input?: Readonly<Record<string, unknown>>): Promise<unknown>;
  listIysCampaigns(input?: Readonly<Record<string, unknown>>): Promise<unknown>;
  listSenderIds(input?: Readonly<Record<string, unknown>>): Promise<unknown>;
  send(input?: Readonly<Record<string, unknown>>): Promise<string>;
  sendLegacy(input?: Readonly<Record<string, unknown>>): Promise<string>;
  status(input?: Readonly<Record<string, unknown>>): Promise<unknown>;
  submitIysConsents(input?: Readonly<Record<string, unknown>>): Promise<string>;
}

export function createSmsFacade(transport: FacadeTransport): SmsFacade {
  return {
    addBlacklistEntry: async (input = {}) =>
      transport.request({"operationId":"post_v2_blacklists","method":"POST","path":"/v2/blacklists","parameters":[{"wireName":"phones","publicName":"phones","location":"query","required":true}],"hasBody":false,"bodyRequiredFields":[],"contentType":null,"responseKind":"text","clientDefaults":{},"credentials":{"password":"query","username":"query"}}, input) as Promise<string>,
    balance: async (input = {}) =>
      transport.request({"operationId":"get_v2_balance","method":"GET","path":"/v2/balance","parameters":[],"hasBody":false,"bodyRequiredFields":[],"contentType":null,"responseKind":"text","clientDefaults":{},"credentials":{"password":"query","username":"query"}}, input) as Promise<string>,
    cancel: async (input = {}) =>
      transport.request({"operationId":"post_v2_cancel_id","method":"POST","path":"/v2/cancel/{id}","parameters":[{"wireName":"id","publicName":"id","location":"path","required":true}],"hasBody":true,"bodyRequiredFields":["username","password"],"contentType":"application/json","responseKind":"text","clientDefaults":{},"credentials":{"password":"body","username":"body"}}, input) as Promise<string>,
    deleteBlacklistEntry: async (input = {}) =>
      transport.request({"operationId":"delete_v2_blacklists_id","method":"DELETE","path":"/v2/blacklists/{id}","parameters":[{"wireName":"id","publicName":"id","location":"path","required":true}],"hasBody":false,"bodyRequiredFields":[],"contentType":null,"responseKind":"text","clientDefaults":{},"credentials":{"password":"query","username":"query"}}, input) as Promise<string>,
    listBlacklistEntries: async (input = {}) =>
      transport.request({"operationId":"get_v2_blacklists","method":"GET","path":"/v2/blacklists","parameters":[{"wireName":"offset","publicName":"offset","location":"query","required":false},{"wireName":"limit","publicName":"limit","location":"query","required":false}],"hasBody":false,"bodyRequiredFields":[],"contentType":null,"responseKind":"json","clientDefaults":{},"credentials":{"password":"query","username":"query"}}, input) as Promise<unknown>,
    listInboundMessages: async (input = {}) =>
      transport.request({"operationId":"get_v2_inbound_messages","method":"GET","path":"/v2/inbound_messages","parameters":[{"wireName":"from_time","publicName":"fromTime","location":"query","required":false},{"wireName":"to_time","publicName":"toTime","location":"query","required":false},{"wireName":"greater_than","publicName":"greaterThan","location":"query","required":false}],"hasBody":false,"bodyRequiredFields":[],"contentType":null,"responseKind":"json","clientDefaults":{},"credentials":{"password":"query","username":"query"}}, input) as Promise<unknown>,
    listIysCampaignConsents: async (input = {}) =>
      transport.request({"operationId":"get_v2_iys_campaigns_id_consents","method":"GET","path":"/v2/iys/campaigns/{id}/consents","parameters":[{"wireName":"id","publicName":"id","location":"path","required":true},{"wireName":"offset","publicName":"offset","location":"query","required":false},{"wireName":"limit","publicName":"limit","location":"query","required":false}],"hasBody":false,"bodyRequiredFields":[],"contentType":null,"responseKind":"json","clientDefaults":{},"credentials":{"password":"query","username":"query"}}, input) as Promise<unknown>,
    listIysCampaigns: async (input = {}) =>
      transport.request({"operationId":"get_v2_iys_campaigns","method":"GET","path":"/v2/iys/campaigns","parameters":[{"wireName":"offset","publicName":"offset","location":"query","required":false},{"wireName":"limit","publicName":"limit","location":"query","required":false},{"wireName":"source","publicName":"source","location":"query","required":false}],"hasBody":false,"bodyRequiredFields":[],"contentType":null,"responseKind":"json","clientDefaults":{},"credentials":{"password":"query","username":"query"}}, input) as Promise<unknown>,
    listSenderIds: async (input = {}) =>
      transport.request({"operationId":"get_v2_headers","method":"GET","path":"/v2/headers","parameters":[],"hasBody":false,"bodyRequiredFields":[],"contentType":null,"responseKind":"json","clientDefaults":{},"credentials":{"password":"query","username":"query"}}, input) as Promise<unknown>,
    send: async (input = {}) =>
      transport.request({"operationId":"sendSmsJson","method":"POST","path":"/v2/send.json","parameters":[],"hasBody":true,"bodyRequiredFields":["username","password","messages"],"contentType":"application/json","responseKind":"text","clientDefaults":{"source_addr":"sourceAddr"},"credentials":{"password":"body","username":"body"}}, input) as Promise<string>,
    sendLegacy: async (input = {}) =>
      transport.request({"operationId":"get_v2_send","method":"GET","path":"/v2/send","parameters":[{"wireName":"dest","publicName":"dest","location":"query","required":true},{"wireName":"msg","publicName":"msg","location":"query","required":true},{"wireName":"source_addr","publicName":"sourceAddr","location":"query","required":false},{"wireName":"valid_for","publicName":"validFor","location":"query","required":false},{"wireName":"datacoding","publicName":"datacoding","location":"query","required":false},{"wireName":"is_commercial","publicName":"isCommercial","location":"query","required":false},{"wireName":"iys_recipient_type","publicName":"iysRecipientType","location":"query","required":false},{"wireName":"send_at","publicName":"sendAt","location":"query","required":false}],"hasBody":false,"bodyRequiredFields":[],"contentType":null,"responseKind":"text","clientDefaults":{"source_addr":"sourceAddr"},"credentials":{"password":"query","username":"query"}}, input) as Promise<string>,
    status: async (input = {}) =>
      transport.request({"operationId":"getSmsStatus","method":"GET","path":"/v2/status","parameters":[{"wireName":"id","publicName":"id","location":"query","required":false},{"wireName":"dest","publicName":"dest","location":"query","required":false},{"wireName":"greater_than","publicName":"greaterThan","location":"query","required":false},{"wireName":"custom_id","publicName":"customId","location":"query","required":false}],"hasBody":false,"bodyRequiredFields":[],"contentType":null,"responseKind":"json","clientDefaults":{},"credentials":{"password":"query","username":"query"}}, input) as Promise<unknown>,
    submitIysConsents: async (input = {}) =>
      transport.request({"operationId":"post_v2_iys_consents_json","method":"POST","path":"/v2/iys_consents.json","parameters":[],"hasBody":true,"bodyRequiredFields":["username","password","source_addr","consents"],"contentType":"application/json","responseKind":"text","clientDefaults":{"source_addr":"sourceAddr"},"credentials":{"password":"body","username":"body"}}, input) as Promise<string>
  };
}
