// Package verimorwhatsapp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package verimorwhatsapp

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/oapi-codegen/runtime"
	"io"
	"net/http"
	"net/url"
	"strings"
)

func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}
func (t ValidationError_Loc_Item) MarshalJSON() ([]byte,// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
error) {
	b, err := t.union.MarshalJSON()
	return b, err
}
func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

func (c *Client) SendOtpV1MessagesOtpPostWithBody(ctx context.Context, params *SendOtpV1MessagesOtpPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendOtpV1MessagesOtpPostRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendOtpV1MessagesOtpPost(ctx context.Context, params *SendOtpV1MessagesOtpPostParams, body SendOtpV1MessagesOtpPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendOtpV1MessagesOtpPostRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendUtilityV1MessagesUtilityPostWithBody(ctx context.Context, params *SendUtilityV1MessagesUtilityPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendUtilityV1MessagesUtilityPostRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendUtilityV1MessagesUtilityPost(ctx context.Context, params *SendUtilityV1MessagesUtilityPostParams, body SendUtilityV1MessagesUtilityPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendUtilityV1MessagesUtilityPostRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func NewSendOtpV1MessagesOtpPostRequest(server string, params *SendOtpV1MessagesOtpPostParams, body SendOtpV1MessagesOtpPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendOtpV1MessagesOtpPostRequestWithBody(server, params, "application/json", bodyReader)
}

func NewSendOtpV1MessagesOtpPostRequestWithBody(server string, params *SendOtpV1MessagesOtpPostParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/v1/messages/otp")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Add("Content-Type", contentType)
	if params != nil {
		if params.XApiKey != nil {
			var headerParam0 string
			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-api-key", *params.XApiKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "", Format: ""})
			if err != nil {
				return nil, err
			}
			req.Header.Set("x-api-key", headerParam0)
		}
	}
	return req, nil
}

func NewSendUtilityV1MessagesUtilityPostRequest(server string, params *SendUtilityV1MessagesUtilityPostParams, body SendUtilityV1MessagesUtilityPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendUtilityV1MessagesUtilityPostRequestWithBody(server, params, "application/json", bodyReader)
}

func NewSendUtilityV1MessagesUtilityPostRequestWithBody(server string, params *SendUtilityV1MessagesUtilityPostParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}
	operationPath := fmt.Sprintf("/v1/messages/utility")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}
	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Add("Content-Type", contentType)
	if params != nil {
		if params.XApiKey != nil {
			var headerParam0 string
			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-api-key", *params.XApiKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "", Format: ""})
			if err != nil {
				return nil, err
			}
			req.Header.Set("x-api-key", headerParam0)
		}
	}
	return req, nil
}

func (r SendOtpV1MessagesOtpPostResponse) GetJSON202() *MessageResponse {
	return r.JSON202
}

func (r SendOtpV1MessagesOtpPostResponse) GetJSON422() *HTTPValidationError {
	return r.JSON422
}

func (r SendOtpV1MessagesOtpPostResponse) GetBody() []byte {// SendOtpV1MessagesOtpPostWithBody OTP / Kimlik Doğrulama Mesajı Gönder
	//
	// WhatsApp AUTHENTICATION kategorisindeki onaylı şablon ile OTP veya kimlik doğrulama mesajı gönderir. Yüksek öncelikli kuyruğa (`high_priority_otp`) yönlendirilir.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/messages/otp (the `SendOtpV1MessagesOtpPost` operationId).
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r SendOtpV1MessagesOtpPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r SendOtpV1MessagesOtpPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r SendOtpV1MessagesOtpPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (r SendUtilityV1MessagesUtilityPostResponse) GetJSON202() *MessageResponse {
	return r.JSON202
}

func (r SendUtilityV1MessagesUtilityPostResponse) GetJSON422() *HTTPValidationError {
	return r.JSON422
}

func (r SendUtilityV1MessagesUtilityPostResponse) GetBody() []byte {// Status returns HTTPResponse.Status
	// GetBody returns the raw response body bytes

	return r.Body
}

func (r SendUtilityV1MessagesUtilityPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

func (r SendUtilityV1MessagesUtilityPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

func (r SendUtilityV1MessagesUtilityPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

func (c *ClientWithResponses) SendOtpV1MessagesOtpPostWithBodyWithResponse(ctx context.Context, params *SendOtpV1MessagesOtpPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendOtpV1MessagesOtpPostResponse, error) {
	rsp, err := c.SendOtpV1MessagesOtpPostWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendOtpV1MessagesOtpPostResponse(rsp)
}

func (c *ClientWithResponses) SendOtpV1MessagesOtpPostWithResponse(ctx context.Context, params *SendOtpV1MessagesOtpPostParams, body SendOtpV1MessagesOtpPostJSONRequestBody, reqEditors ...RequestEditorFn) (*SendOtpV1MessagesOtpPostResponse, error) {
	rsp, err := c.SendOtpV1MessagesOtpPost(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendOtpV1MessagesOtpPostResponse(rsp)
}

func (c *ClientWithResponses) SendUtilityV1MessagesUtilityPostWithBodyWithResponse(ctx context.Context, params *SendUtilityV1MessagesUtilityPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendUtilityV1MessagesUtilityPostResponse, error) {
	rsp, err := c.SendUtilityV1MessagesUtilityPostWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendUtilityV1MessagesUtilityPostResponse(rsp)
}

func (c *ClientWithResponses) SendUtilityV1MessagesUtilityPostWithResponse(ctx context.Context, params *SendUtilityV1MessagesUtilityPostParams, body SendUtilityV1MessagesUtilityPostJSONRequestBody, reqEditors ...RequestEditorFn) (*SendUtilityV1MessagesUtilityPostResponse, error) {
	rsp, err := c.SendUtilityV1MessagesUtilityPost(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendUtilityV1MessagesUtilityPostResponse(rsp)
}

func ParseSendOtpV1MessagesOtpPostResponse(rsp *http.Response) (*SendOtpV1MessagesOtpPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &SendOtpV1MessagesOtpPostResponse{Body: bodyBytes, HTTPResponse: rsp}
	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest MessageResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest
	}
	return response, nil
}

func ParseSendUtilityV1MessagesUtilityPostResponse(rsp *http.Response) (*SendUtilityV1MessagesUtilityPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() {
		_ = rsp.Body.Close()
	}()
	if err != nil {
		return nil, err
	}
	response := &SendUtilityV1MessagesUtilityPostResponse{Body: bodyBytes, HTTPResponse: rsp}
	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest MessageResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest
	}
	return response, nil
}

// Status returns HTTPResponse.Status
// ParseSendUtilityV1MessagesUtilityPostResponse parses an HTTP response from a SendUtilityV1MessagesUtilityPostWithResponse call
